(*L001_02__Aporetic_Obstruction.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                  Proofcase / L001_02__Aporetic_Obstruction                   │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  Obstruction layer: consistency rejects the bottom produced from a negation
  fixed point, modus ponens, and a local accepted branch.

  The generic result is followed by M001 regulator, yes-status, and optional
  double-negation no-status forms.

*)

From L001 Require Export L001_01__Aporetic_Lemma.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                             CONSISTENCY BOUNDARY                             │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          `RegulatorClosureConsistent profile T Gamma` is the M001
│          instance of closure consistency. It says that the regulator
│          closure generated by `profile`, `T`, and `Gamma` cannot
│          accept object-level bottom without contradicting the
│          ambient Rocq context.
│
*)

(*RegulatorClosureConsistent(profile,T,Γ) ≔ RegulatorClosure(profile,T,Γ,⊥) → *)
(*                                   False.                                   *)

Definition RegulatorClosureConsistent
    (profile : RegulatorLogicProfile)
    (T : AxiomSet)
    (Gamma : Context) : Prop :=
  ClosureConsistent (RegulatorClosure profile T Gamma).

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                             GENERIC OBSTRUCTION                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          The local branch collapse yields `C Bot`; consistency turns
│          it into `False`.
│
*)

(*    Consistent(C) ∧ ModusPonens(C) ∧ NegFP_C(B) ∧ LocalLEM_C(B) ⇒ False.    *)

Theorem core_diagonal_obstruction :
  forall (C : Formula -> Prop) B,
    ClosureModusPonens C ->
    ClosureConsistent C ->
    NegationFixedPointFor C B ->
    ClosureLocalExcludedMiddle C B ->
    False.
Proof.
  intros C B Hmodus_ponens Hconsistent Hfixed_point Hlocal.
  apply Hconsistent.
  exact
    (local_branch_collapse
       C B Hmodus_ponens Hfixed_point Hlocal).
Qed.

(*
│
│          A negation fixed point blocks closure-level excluded middle
│          under consistency because global excluded middle supplies
│          the required local branch datum at the fixed point.
│
*)

(*  Consistent(C) ∧ ModusPonens(C) ∧ (B ≃_C ¬B) ∧ ExcludedMiddle(C) ⇒ False.  *)

Theorem negfixp_obstructs_lem :
  forall (C : Formula -> Prop) B,
    ClosureConsistent C ->
    ClosureModusPonens C ->
    NegationFixedPointFor C B ->
    ClosureExcludedMiddle C ->
    False.
Proof.
  intros C B Hconsistent Hmodus_ponens Hfixed_point Hexcluded_middle.
  exact
    (core_diagonal_obstruction
       C B Hmodus_ponens Hconsistent Hfixed_point
       (closure_lem_to_local_lemma C B Hexcluded_middle)).
Qed.

(*
│
│          Full-frame corollary. Full evaluation first yields the
│          bottom goal frame; the bottom goal frame produces the local
│          diagonal datum; global excluded middle supplies the local
│          branch at that datum; the core obstruction does the rest.
│
*)

(*   Consistent(C) ∧ ModusPonens(C) ∧ EvalComplete(C) ∧ ExcludedMiddle(C) ⇒   *)
(*                                   False.                                   *)

Theorem full_frame_obstruction_corollary :
  forall (C : Formula -> Prop) Code
         (E : ClosureEvaluationFrame C Code),
    ClosureConsistent C ->
    ClosureModusPonens C ->
    ClosureExcludedMiddle C ->
    False.
Proof.
  intros C Code E Hconsistent Hmodus_ponens Hexcluded_middle.
  destruct
    (eval_bottom_negfixp
       C Code (ceval_apply E)
       (eval_full_to_eval_bottom C Code E))
    as [B Hfixed_point].
  exact
    (core_diagonal_obstruction
       C B Hmodus_ponens Hconsistent Hfixed_point
       (closure_lem_to_local_lemma C B Hexcluded_middle)).
Qed.

(*
│
│          Compatibility spelling retained for older clients: the
│          former aporetic obstruction is now the full-frame corollary
│          of the local obstruction.
│
*)

Theorem aporetic_obstruction :
  forall (C : Formula -> Prop) Code
         (E : ClosureEvaluationFrame C Code),
    ClosureConsistent C ->
    ClosureModusPonens C ->
    ClosureExcludedMiddle C ->
    False.
Proof.
  exact full_frame_obstruction_corollary.
Qed.

(*
│
│          Closure-acceptance undecidability: evaluation, modus
│          ponens, and consistency exclude a total Boolean decision
│          certified internally by `C A` or `C (¬A)`.
│
*)

(* Consistent(C) ∧ ModusPonens(C) ∧ EvalComplete(C) ⇒ ¬∃d. (d(A)=true⇒C(A)) ∧ *)
(*                            (d(A)=false⇒C(¬A)).                             *)

Theorem closure_acceptance_undecidable_theorem :
  forall (C : Formula -> Prop) Code
         (E : ClosureEvaluationFrame C Code),
    ClosureConsistent C ->
    ClosureModusPonens C ->
    ~ exists d : Formula -> bool,
        (forall A, d A = true -> C A) /\
        (forall A, d A = false -> C (formula_negation A)).
Proof.
  intros C Code E Hconsistent Hmodus_ponens
    [decide_accepts [Htrue_sound Hfalse_sound]].
  apply
    (aporetic_obstruction
       C Code E Hconsistent Hmodus_ponens).
  intro A.
  destruct (decide_accepts A) eqn:Hdecide.
  - left.
    exact (Htrue_sound A Hdecide).
  - right.
    exact (Hfalse_sound A Hdecide).
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                            REGULATOR OBSTRUCTION                             │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          The previous generic obstruction specializes to the M001
│          regulator closure. The only regulator-specific input is the
│          M001 modus-ponens lemma for `RegulatorClosure`.
│
*)

(*                RegulatorClosureConsistent(profile,T,Γ) ∧ B                 *)
(*                   ≃_{RegulatorClosure(profile,T,Γ)} ¬B ∧                   *)
(*            RegulatorClosureExcludedMiddle(profile,T,Γ) ⇒ False.            *)

Theorem negfixp_obstructs_regulator_lem :
  forall profile T Gamma B,
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorNegationFixedPoint profile T Gamma B ->
    RegulatorClosureExcludedMiddle profile T Gamma ->
    False.
Proof.
  intros profile T Gamma B Hconsistent Hfixed_point Hexcluded_middle.
  exact
    (negfixp_obstructs_lem
       (RegulatorClosure profile T Gamma)
       B
       Hconsistent
       (regulator_closure_modus_ponens_lemma profile T Gamma)
       Hfixed_point
       ((proj1
           (regulator_lem_iff_closure_lem
              profile T Gamma))
          Hexcluded_middle)).
Qed.

(*
│
│          A total regulator positive/negative accepted-branch
│          classifier carries more data than regulator-level
│          excluded-middle completeness. Therefore a negation fixed
│          point and consistency already obstruct such a classifier.
│
*)

(*       RegulatorClosureConsistent ∧ RegulatorNegationFixedPoint(B) ∧        *)
(*                         RegulatorDecision ⇒ False.                         *)

Theorem negfixp_obstructs_regulator_decision :
  forall profile T Gamma B,
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorNegationFixedPoint profile T Gamma B ->
    RegulatorDecision profile T Gamma ->
    False.
Proof.
  intros profile T Gamma B Hconsistent Hfixed_point D.
  exact
    (negfixp_obstructs_regulator_lem
       profile T Gamma B Hconsistent Hfixed_point
       (regulator_decision_to_lem profile T Gamma D)).
Qed.

(*
│
│          Regulated evaluation closure obstructs regulator-level
│          excluded middle under consistency. This is the
│          regulator-facing form of the main obstruction: evaluation
│          closure gives the diagonal, excluded middle chooses a
│          branch, and consistency rejects the resulting bottom
│          formula.
│
*)

(*       RegulatorClosureEvaluationFrame ∧ RegulatorClosureConsistent ∧       *)
(*                  RegulatorClosureExcludedMiddle ⇒ False.                   *)

Theorem regulator_aporetic_obstruction :
  forall profile T Gamma Code
         (E : RegulatorClosureEvaluationFrame profile T Gamma Code),
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorClosureExcludedMiddle profile T Gamma ->
    False.
Proof.
  intros profile T Gamma Code E Hconsistent Hexcluded_middle.
  exact
    (aporetic_obstruction
       (RegulatorClosure profile T Gamma)
       Code
       (regulator_closure_evaluation_frame
          profile T Gamma Code E)
       Hconsistent
       (regulator_closure_modus_ponens_lemma profile T Gamma)
       ((proj1
           (regulator_lem_iff_closure_lem
              profile T Gamma))
          Hexcluded_middle)).
Qed.

(*
│
│          The accepted-branch-classifier obstruction is the Boolean
│          version of the previous theorem. The classifier first
│          yields `RegulatorClosure Bot`, and the consistency
│          hypothesis is used only after that collapse has been
│          obtained.
│
*)

(*       RegulatorClosureEvaluationFrame ∧ RegulatorClosureConsistent ∧       *)
(*                         RegulatorDecision ⇒ False.                         *)

Theorem regulator_decision_obstruction :
  forall profile T Gamma Code
         (E : RegulatorClosureEvaluationFrame profile T Gamma Code),
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorDecision profile T Gamma ->
    False.
Proof.
  intros profile T Gamma Code E Hconsistent D.
  destruct
    (regulator_decision_collapse
       profile T Gamma Code E D)
    as [B [_fixed_point [_branch Hbottom]]].
  exact (Hconsistent Hbottom).
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                            YES-BRANCH OBSTRUCTION                            │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          The yes-status branch is obstructed when its acceptance
│          supplies `RegulatorDecision`.
│
*)

(*                 RegulatorClosure(excluded_middle_status) ∧                 *)
(*  (RegulatorClosure(excluded_middle_status) → RegulatorDecision) ⇒ False.   *)

Theorem aporetic_status_yes_obstructed_lemma :
  forall profile T Gamma Code
         (E : RegulatorClosureEvaluationFrame profile T Gamma Code)
         (excluded_middle_status : Formula),
    RegulatorClosureConsistent profile T Gamma ->
    YesBranchDecides profile T Gamma excluded_middle_status ->
    RegulatorClosure profile T Gamma excluded_middle_status ->
    False.
Proof.
  intros profile T Gamma Code E excluded_middle_status
    Hconsistent Hstatus_to_decision Hstatus.
  apply
    (regulator_decision_obstruction
       profile T Gamma Code E Hconsistent).
  exact (Hstatus_to_decision Hstatus).
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                 NO BRANCH OBSTRUCTION UNDER DOUBLE NEGATION                  │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          No-branch obstruction requires an extra principle. If the
│          regulator accepts `¬¬excluded_middle_status` and a
│          double-negation bridge is available, the bridge derives
│          `excluded_middle_status`; together with an accepted
│          `¬excluded_middle_status`, one final modus-ponens step
│          yields bottom.
│
*)

(*        RegulatorClosureConsistent ∧ RegulatorDoubleNegationBridge ∧        *)
(*           RegulatorClosure(¬¬S) ∧ RegulatorClosure(¬S) ⇒ False.            *)

Theorem aporetic_status_no_blocked_by_double_negation_lemma :
  forall profile T Gamma (excluded_middle_status : Formula),
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorDoubleNegationBridge profile T Gamma ->
    RegulatorClosure profile T Gamma (formula_negation (formula_negation excluded_middle_status)) ->
    RegulatorClosure profile T Gamma (formula_negation excluded_middle_status) ->
    False.
Proof.
  intros profile T Gamma excluded_middle_status
    Hconsistent Hdouble_negation_bridge Hdouble_negated_status Hnegated_status.
  apply Hconsistent.
  exact
    (regulator_closure_modus_ponens_lemma profile T Gamma
       excluded_middle_status Bot Hnegated_status
       (Hdouble_negation_bridge
          excluded_middle_status
          Hdouble_negated_status)).
Qed.

(*
│
│          The bridge-incompatibility form says the same fact
│          contrapositively at the status formula. Under consistency
│          and an accepted no branch, a double-negation bridge
│          prevents the regulator from also accepting
│          `¬¬excluded_middle_status`.
│
*)

(*            RegulatorClosureConsistent ∧ RegulatorClosure(¬S) ∧             *)
(*          RegulatorDoubleNegationBridge ⇒ ¬ RegulatorClosure(¬¬S).          *)

Theorem aporetic_status_no_excludes_double_negation_lemma :
  forall profile T Gamma (excluded_middle_status : Formula),
    RegulatorClosureConsistent profile T Gamma ->
    RegulatorClosure profile T Gamma (formula_negation excluded_middle_status) ->
    RegulatorDoubleNegationBridge profile T Gamma ->
    RegulatorClosure profile T Gamma (formula_negation (formula_negation excluded_middle_status)) ->
    False.
Proof.
  intros profile T Gamma excluded_middle_status
    Hconsistent Hnegated_status Hdouble_negation_bridge Hdouble_negated_status.
  exact
    (aporetic_status_no_blocked_by_double_negation_lemma
       profile T Gamma excluded_middle_status
       Hconsistent
       Hdouble_negation_bridge
       Hdouble_negated_status
       Hnegated_status).
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                         REFUTATION DOES NOT COLLAPSE                         │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          A refutation-only classifier is vacuously sound when it
│          always returns `false`. Aporetic collapse requires a
│          positive accepted branch, which the false-on-all classifier
│          never supplies.
│
*)

(*           ∃ R : RegulatorRefutation, ∀ A, rrefute(R, A) = false.           *)

Lemma always_false_refutation_sound :
  forall profile T Gamma A,
    (fun _ : Formula => false) A = true ->
    RegulatorClosure profile T Gamma (formula_negation A).
Proof.
  intros profile T Gamma A Htrue.
  discriminate Htrue.
Qed.

(* The always-false classifier is the canonical witness for refutation-only
   non-collapse. Its soundness field is unreachable by computation. *)
Definition always_false_regulator_refutation
    (profile : RegulatorLogicProfile)
    (T : AxiomSet)
    (Gamma : Context)
    : RegulatorRefutation profile T Gamma :=
  {|
    rrefute := fun _ => false;
    rrefute_true_sound := always_false_refutation_sound profile T Gamma
  |}.

(*
│
│          The always-false refutation witness shows that the decision
│          obstruction does not extend to refutation-only classifiers.
│
*)

(*RegulatorClosureConsistent ⇒ ∃ R : RegulatorRefutation, ∀ A, rrefute(R, A) =*)
(*                                   false.                                   *)

Theorem refutation_not_obstructed :
  forall profile T Gamma,
    RegulatorClosureConsistent profile T Gamma ->
    exists R : RegulatorRefutation profile T Gamma,
      forall A, rrefute R A = false.
Proof.
  intros profile T Gamma _Hconsistent.
  exists (always_false_regulator_refutation profile T Gamma).
  intro A.
  reflexivity.
Qed.
