(*P002_00_Premises.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                         Proofcase / P002_00_Premises                         │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  This file is the canonical semantic surface of the P002 problem statement.
  Its role is to fix, in an immutable form, (i) the low-degree atomic
  equation language emitted by the Iterant/FM compilation layers, (ii) the
  family-level satisfiability language that is the current semantic ground
  truth of P002, (iii) the extensional notion of decider against which the
  public endpoint is stated, and (iv) the target predicates that the later
  certification layers actually use.

  No later file in the development is permitted to redefine any of the
  notions introduced here; downstream layers may only build on top of them.
  This file is intentionally assumption-free at the problem layer: it fixes
  syntax, semantics, and the public yes-languages, but leaves all reduction
  work to later files.

  The file is organized in six sections: proof environment, low-degree atomic
  syntax, well-formedness, semantics, the extensional solver notion, and the
  public target statements. The atomic language happens to be cubic because
  that is the local degree bound generated by the Iterant/FM arithmetic; the
  semantic message of the file is not “P002 is about one cubic equation” but
  rather “the retained P002 endpoint is satisfiability of finite low-degree
  families over one shared valuation”.

*)

(*
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│                            PROOF ENVIRONMENT                            │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          This premise layer imports only standard arithmetic and
│          list syntax. It introduces no local axioms, no classical
│          choice principle, and no proof-theoretic assumption; all
│          project-specific assumptions appear later and are surfaced
│          explicitly by the terminal assumption reports.
│
*)

From Stdlib Require Export Arith List.
Export ListNotations.

(*
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│                             LOW-DEGREE ATOMS                            │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          Syntactic monomials of total degree at most three. The four
│          constructors denote, respectively, the constant monomial 1,
│          a variable xᵢ, a quadratic product xᵢ·xⱼ, and a cubic
│          product xᵢ·xⱼ·xₖ. This cubic bound is a local normal form
│          coming from the Iterant/FM compilation surface; it is not
│          itself the final semantic claim of P002. Variable indices
│          are drawn from ℕ without restriction at this level; their
│          admissibility relative to a specific equation's arity is
│          enforced separately by the well-formedness predicate in the
│          next section.
│
*)

(*            monomial ::= 1 ∣ xᵢ ∣ xᵢ·xⱼ ∣ xᵢ·xⱼ·xₖ (i, j, k ∈ ℕ)            *)

Inductive monomial : Type :=
| m_const
| m_linear (i : nat)
| m_quadratic (i j : nat)
| m_cubic (i j k : nat).

(*
│
│          A term pairs a natural-number coefficient with a monomial.
│          Restricting coefficients to ℕ is a deliberate normal-form
│          choice: any cubic Diophantine equation with integer
│          coefficients can be rewritten, without loss of generality,
│          as an equality of two sums of ℕ-coefficient monomials by
│          moving negative summands to the opposite side.
│
*)

(*                  term ≔ (c, μ) with c ∈ ℕ, μ a monomial;                   *)
(*                               ⟦term⟧ ≡ c · μ                               *)

Record term : Type := {
  coeff : nat;
  mono : monomial
}.

(*
│
│          An equation is a triple consisting of a declared arity and
│          two lists of terms representing the left- and right-hand
│          sides. Writing equations in the form LHS = RHS, rather than
│          P = 0, is what permits both sides to range over ℕ and is
│          the necessary counterpart of the ℕ-coefficient normal form
│          adopted above.
│
*)

(*                       Equation₃ ≔ ⟨n, Σᵢ lᵢ, Σⱼ rⱼ⟩                        *)
(*              n ∈ ℕ; each term has degree ≤ 3 over x₀, …, xₙ₋₁              *)

Record h10_nd3n_equation : Type := {
  var_count : nat;
  lhs_terms : list term;
  rhs_terms : list term
}.

(*
│
│          A valuation assigns a natural number to every variable
│          index. Representing valuations as total functions ℕ → ℕ,
│          rather than as finite vectors, removes the need to carry an
│          arity proof alongside each valuation; values at indices
│          outside the declared arity of a given equation are
│          inaccessible to that equation by well-formedness and are
│          therefore immaterial.
│
*)

(*                           valuation ≔ ρ : ℕ → ℕ                            *)

Definition valuation : Type := nat -> nat.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                             WELL-FORMEDNESS                             ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          A monomial is well-formed at arity n when every variable
│          index occurring in it is strictly less than n; the constant
│          monomial is vacuously well-formed. The predicate serves
│          solely to rule out ill-scoped syntax and imposes no
│          arithmetic constraint on valuations.
│
*)

(*       WFₘ(n, μ) ⇔ every index occurring in μ is strictly less than n       *)

Definition monomial_wf (n : nat) (m : monomial) : Prop :=
  match m with
  | m_const => True
  | m_linear i => i < n
  | m_quadratic i j => i < n /\ j < n
  | m_cubic i j k => i < n /\ j < n /\ k < n
  end.

(*
│
│          An equation is well-formed when every term occurring on
│          either side uses only variable indices below its declared
│          arity. Well-formedness is incorporated into the definition
│          of `solves` below, so that no downstream result of this
│          file applies to ill-formed instances.
│
*)

(*               WFₑ(⟨n, L, R⟩) ⇔ ∀ t ∈ L ⊕ R. WFₘ(n, mono(t))                *)

Definition equation_wf (eqn : h10_nd3n_equation) : Prop :=
  Forall (fun t => monomial_wf (var_count eqn) (mono t)) (lhs_terms eqn) /\
  Forall (fun t => monomial_wf (var_count eqn) (mono t)) (rhs_terms eqn).

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                                SEMANTICS                                ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          Denotational semantics of a monomial under a valuation. The
│          constant monomial evaluates to 1, and linear, quadratic,
│          and cubic monomials evaluate to the corresponding products
│          of variable values. All operations are performed in ℕ, so
│          evaluation never escapes the natural numbers.
│
*)

(*                ⟦1⟧ρ = 1, ⟦xᵢ⟧ρ = ρ(i), ⟦xᵢxⱼ⟧ρ = ρ(i)·ρ(j),                *)
(*                         ⟦xᵢxⱼxₖ⟧ρ = ρ(i)·ρ(j)·ρ(k)                         *)

Definition eval_monomial (rho : valuation) (m : monomial) : nat :=
  match m with
  | m_const => 1
  | m_linear i => rho i
  | m_quadratic i j => rho i * rho j
  | m_cubic i j k => rho i * rho j * rho k
  end.

(*
│
│          The value of a term under a valuation is the product of its
│          coefficient and the value of its monomial.
│
*)

(*                            ⟦(c, μ)⟧ρ = c · ⟦μ⟧ρ                            *)

Definition eval_term (rho : valuation) (t : term) : nat :=
  coeff t * eval_monomial rho (mono t).

(*
│
│          A list of terms denotes the sum of the individual term
│          values under the given valuation. The fold is initialized
│          at 0, so that an empty list denotes the empty sum, in
│          agreement with the standard mathematical convention.
│
*)

(*                ⟦[t₁, …, tₘ]⟧ρ = Σᵢ₌₁ᵐ ⟦tᵢ⟧ρ, with ⟦[]⟧ρ = 0                *)

Definition eval_poly (ts : list term) (rho : valuation) : nat :=
  fold_right (fun t acc => eval_term rho t + acc)%nat 0 ts.

(*
│
│          A valuation is said to solve an equation when the equation
│          is well-formed and its two sides evaluate to the same
│          natural number under that valuation. Well-formedness is
│          incorporated directly into the solution relation, ensuring
│          that solvability can never be witnessed by the evaluation
│          of a malformed syntactic object.
│
*)

(*            Solves(⟨n, L, R⟩, ρ) ⇔ WFₑ(⟨n, L, R⟩) ∧ ⟦L⟧ρ = ⟦R⟧ρ             *)

Definition solves (eqn : h10_nd3n_equation) (rho : valuation) : Prop :=
  equation_wf eqn /\
  eval_poly (lhs_terms eqn) rho = eval_poly (rhs_terms eqn) rho.

(*
│
│          An equation is solvable over ℕ when it admits at least one
│          solving valuation. This existential closure is the atomic
│          yes-language used inside the finite-family semantics below.
│
*)

(*                  Solvable(E) ⇔ ∃ ρ : ℕ → ℕ. Solves(E, ρ)                   *)

Definition solvable_over_nat (eqn : h10_nd3n_equation) : Prop :=
  exists rho : valuation, solves eqn rho.

(*
│
│          A problem instance is, by definition, an equation in the
│          form fixed above. The alias is introduced so that
│          downstream files can consistently refer to `instances` at
│          the problem-theoretic layer while `equations` remains a
│          purely syntactic notion.
│
*)

Definition h10_nd3n_instance : Type := h10_nd3n_equation.

(*
│
│          Atomic yes-predicate for one low-degree equation over ℕ in
│          the current FM normal form. This remains in the premise
│          layer because local emitter files and later reductions
│          still manipulate single equations as atoms, but it is not
│          the principal semantic yes-language of P002.
│
*)

(*                    Yes₃(E) ⇔ ∃ ρ : ℕ → ℕ. Solves(E, ρ)                     *)

Definition h10_nd3n_yes (eqn : h10_nd3n_instance) : Prop :=
  solvable_over_nat eqn.

(*
│
│          A family instance is a finite list of atomic low-degree
│          equations. The shared-valuation condition belongs to the
│          satisfiability predicate below, not to the raw list type
│          itself.
│
*)

(*                            Family₃ ≔ [E₁, …, Eₘ                            *)

Definition cubic_family_instance : Type := list h10_nd3n_equation.

(*
│
│          A cubic family is satisfiable when one valuation solves
│          every equation in the list. This is the semantic ground
│          truth of the frozen P002 development: the Iterant/FM
│          compilation layers land here directly, and the terminal
│          theorem states bounded Σ₁-completeness at this family
│          level.
│
*)

(*                 FamilyYes(Γ) ⇔ ∃ ρ. ∀ E ∈ Γ. Solves(E, ρ)                  *)

Definition cubic_family_yes (Gamma : cubic_family_instance) : Prop :=
  exists rho : valuation, Forall (fun eqn => solves eqn rho) Gamma.

(*
│
│          The principal semantic instance type of the frozen P002
│          project is the family language, not a single-equation
│          language. The alias below is the public project-level name
│          for that concrete family type.
│
*)

(*                           P002Instance ≔ Family₃                           *)

Definition p002_instance : Type := cubic_family_instance.

(*
│
│          The project-level yes-predicate is exactly family
│          satisfiability. This alias is the public P002 name;
│          `cubic_family_yes` remains the concrete semantic predicate
│          it abbreviates.
│
*)

(*                         P002Yes(Γ) ⇔ FamilyYes(Γ)                          *)

Definition p002_yes (Gamma : p002_instance) : Prop :=
  cubic_family_yes Gamma.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                       SOLVER OR METHOD DEFINITION                       ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          The classical, extensional notion of a decider: a boolean
│          function `solver` decides a yes-language `yes` when its set
│          of true-answers coincides exactly with the yes-language. No
│          machine model is fixed here; this file records only the
│          semantic criterion that later undecidability statements
│          negate.
│
*)

(*                decides(yes, f) ⇔ ∀ x. f(x) = true ↔ yes(x)                 *)

Definition decides {X : Type} (yes : X -> Prop) (solver : X -> bool) : Prop :=
  forall x, solver x = true <-> yes x.

(*
│
│          A concrete family solver decides the finite-family language
│          when it decides the predicate `cubic_family_yes`. This is
│          the shape consumed by the downstream compiler theorems.
│
*)

(*                  DecidesFamily(f) ⇔ Decides(FamilyYes, f)                  *)

Definition decides_cubic_family (solver : cubic_family_instance -> bool) : Prop :=
  decides cubic_family_yes solver.

(*
│
│          A project-level solver decides P002 when it decides the
│          public predicate `p002_yes`. This is only an alias layer
│          over the family-level definition above.
│
*)

(*                    DecidesP002(f) ⇔ Decides(P002Yes, f)                    *)

Definition decides_p002 (solver : p002_instance -> bool) : Prop :=
  decides p002_yes solver.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                            TARGET STATEMENTS                            ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          The project-level no-decider target says that no total
│          boolean solver decides `p002_yes`. In this premise file it
│          is only a target statement; later files determine which
│          hypotheses imply it.
│
*)

(*       P002Undecidable ⇔ ∀ f : P002Instance → Bool. ¬ DecidesP002(f)        *)

Definition p002_semantic_undecidable : Prop :=
  forall solver : p002_instance -> bool,
  ~ decides_p002 solver.

(*
│
│          The concrete family-level no-decider target says that no
│          total boolean solver decides finite cubic-family
│          satisfiability. It talks about finite families over one
│          shared valuation, not about a single cubic equation.
│
*)

(*        FamilyUndecidable ⇔ ∀ f : Family₃ → Bool. ¬ DecidesFamily(f)        *)

Definition cubic_family_semantic_undecidable : Prop :=
  forall solver : cubic_family_instance -> bool,
  ~ decides_cubic_family solver.
