(*P002_00_Premises.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                         Proofcase / P002_00_Premises                         │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  This file is the canonical semantic surface of the P002 problem statement.
  Its role is to fix, in an immutable form, (i) the low-degree atomic
  equation language emitted by the carryless Fibonacci/FM compilation layers,
  (ii) the family-level satisfiability language that is the current semantic
  ground truth of P002, (iii) the extensional and coded notions of decider
  against which all downstream claims are stated, and (iv) the target
  predicates that later certification layers may use or compare against,
  including the quartic single-equation route that sits strictly above the
  family layer.

  No later file in the development is permitted to redefine any of the
  notions introduced here; downstream layers may only build on top of them.
  This file is intentionally assumption-free at the problem layer: it may
  declare abstract interfaces such as decoders or evaluators, but any
  non-logical coverage, surjectivity, reduction, or reflection debt must live
  in a rewrite phase or in a later concrete realization layer, not here.

  The file is organized in eight sections: proof environment, low-degree
  atomic syntax, well-formedness, semantics, the extensional solver notion,
  the coded solver notion, the coded-to-extensional communication lemmas, and
  the public target statements. The atomic language happens to be cubic
  because that is the local degree bound generated by the FM carryless
  arithmetic; the semantic message of the file is not “P002 is about cubic
  single equations” but rather “carryless Fibonacci pairing reduces the hard
  part of MRDP to low-degree atomic families, from which the quartic question
  can be approached cleanly”.

*)

(*
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│                            PROOF ENVIRONMENT                            │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          We rely on Rocq's kernel
│
*)

From Stdlib Require Export Arith List.
Export ListNotations.

(*
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│                             LOW-DEGREE ATOMS                            │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
*)

(*
│
│          Syntactic monomials of total degree at most three. The four
│          constructors denote, respectively, the constant monomial 1,
│          a variable xᵢ, a quadratic product xᵢ·xⱼ, and a cubic
│          product xᵢ·xⱼ·xₖ. This cubic bound is a local normal form
│          coming from the FM carryless/Fibonacci compilation surface;
│          it is not itself the final semantic claim of P002. Variable
│          indices are drawn from ℕ without restriction at this level;
│          their admissibility relative to a specific equation's arity
│          is enforced separately by the well-formedness predicate in
│          the next section.
│
*)

(*            monomial ::= 1 ∣ xᵢ ∣ xᵢ·xⱼ ∣ xᵢ·xⱼ·xₖ (i, j, k ∈ ℕ)            *)

Inductive monomial : Type :=
| m_const
| m_linear (i : nat)
| m_quadratic (i j : nat)
| m_cubic (i j k : nat).

(*
│
│          A term pairs a natural-number coefficient with a monomial.
│          Restricting coefficients to ℕ is a deliberate normal-form
│          choice: any cubic Diophantine equation with integer
│          coefficients can be rewritten, without loss of generality,
│          as an equality of two sums of ℕ-coefficient monomials by
│          moving negative summands to the opposite side.
│
*)

(*                  term ≔ (c, μ) with c ∈ ℕ, μ a monomial;                   *)
(*                               ⟦term⟧ ≡ c · μ                               *)

Record term : Type := {
  coeff : nat;
  mono : monomial
}.

(*
│
│          An equation is a triple consisting of a declared arity and
│          two lists of terms representing the left- and right-hand
│          sides. Writing equations in the form LHS = RHS, rather than
│          P = 0, is what permits both sides to range over ℕ and is
│          the necessary counterpart of the ℕ-coefficient normal form
│          adopted above.
│
*)

(*                   h10_nd3n_equation ≔ ⟨n, Σᵢ lᵢ, Σⱼ rⱼ⟩                    *)
(*      with n ∈ ℕ and each lᵢ, rⱼ a degree-≤3 term over x₀, …, x_{n−1}       *)

Record h10_nd3n_equation : Type := {
  var_count : nat;
  lhs_terms : list term;
  rhs_terms : list term
}.

(*
│
│          A valuation assigns a natural number to every variable
│          index. Representing valuations as total functions ℕ → ℕ,
│          rather than as finite vectors, removes the need to carry an
│          arity proof alongside each valuation; values at indices
│          outside the declared arity of a given equation are
│          inaccessible to that equation by well-formedness and are
│          therefore immaterial.
│
*)

(*                           valuation ≔ ρ : ℕ → ℕ                            *)

Definition valuation : Type := nat -> nat.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                             WELL-FORMEDNESS                             ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          A monomial is well-formed at arity n when every variable
│          index occurring in it is strictly less than n; the constant
│          monomial is vacuously well-formed. The predicate serves
│          solely to rule out ill-scoped syntax and imposes no
│          arithmetic constraint on valuations.
│
*)

(*   monomial_wf(n, μ) ⇔ every index occurring in μ is strictly less than n   *)

Definition monomial_wf (n : nat) (m : monomial) : Prop :=
  match m with
  | m_const => True
  | m_linear i => i < n
  | m_quadratic i j => i < n /\ j < n
  | m_cubic i j k => i < n /\ j < n /\ k < n
  end.

(*
│
│          An equation is well-formed when every term occurring on
│          either side uses only variable indices below its declared
│          arity. Well-formedness is incorporated into the definition
│          of `solves` below, so that no downstream result of this
│          file applies to ill-formed instances.
│
*)

(*       equation_wf(⟨n, L, R⟩) ⇔ ∀ t ∈ L ⊕ R. monomial_wf(n, mono(t))        *)

Definition equation_wf (eqn : h10_nd3n_equation) : Prop :=
  Forall (fun t => monomial_wf (var_count eqn) (mono t)) (lhs_terms eqn) /\
  Forall (fun t => monomial_wf (var_count eqn) (mono t)) (rhs_terms eqn).

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                                SEMANTICS                                ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          Denotational semantics of a monomial under a valuation. The
│          constant monomial evaluates to 1, and linear, quadratic,
│          and cubic monomials evaluate to the corresponding products
│          of variable values. All operations are performed in ℕ, so
│          evaluation never escapes the natural numbers.
│
*)

(*                ⟦1⟧ρ = 1, ⟦xᵢ⟧ρ = ρ(i), ⟦xᵢxⱼ⟧ρ = ρ(i)·ρ(j),                *)
(*                         ⟦xᵢxⱼxₖ⟧ρ = ρ(i)·ρ(j)·ρ(k)                         *)

Definition eval_monomial (rho : valuation) (m : monomial) : nat :=
  match m with
  | m_const => 1
  | m_linear i => rho i
  | m_quadratic i j => rho i * rho j
  | m_cubic i j k => rho i * rho j * rho k
  end.

(*
│
│          The value of a term under a valuation is the product of its
│          coefficient and the value of its monomial.
│
*)

(*                            ⟦(c, μ)⟧ρ = c · ⟦μ⟧ρ                            *)

Definition eval_term (rho : valuation) (t : term) : nat :=
  coeff t * eval_monomial rho (mono t).

(*
│
│          A list of terms denotes the sum of the individual term
│          values under the given valuation. The fold is initialized
│          at 0, so that an empty list denotes the empty sum, in
│          agreement with the standard mathematical convention.
│
*)

(*                ⟦[t₁, …, tₘ]⟧ρ = Σᵢ₌₁ᵐ ⟦tᵢ⟧ρ, with ⟦[]⟧ρ = 0                *)

Definition eval_poly (ts : list term) (rho : valuation) : nat :=
  fold_right (fun t acc => eval_term rho t + acc)%nat 0 ts.

(*
│
│          A valuation is said to solve an equation when the equation
│          is well-formed and its two sides evaluate to the same
│          natural number under that valuation. Well-formedness is
│          incorporated directly into the solution relation, ensuring
│          that solvability can never be witnessed by the evaluation
│          of a malformed syntactic object.
│
*)

(*     solves(⟨n, L, R⟩, ρ) ⇔ equation_wf(⟨n, L, R⟩) ∧ ⟦L⟧ρ = ⟦R⟧ρ (in ℕ)     *)

Definition solves (eqn : h10_nd3n_equation) (rho : valuation) : Prop :=
  equation_wf eqn /\
  eval_poly (lhs_terms eqn) rho = eval_poly (rhs_terms eqn) rho.

(*
│
│          An equation is solvable over ℕ when it admits at least one
│          solving valuation. This existential closure is the semantic
│          yes-language of the H10 fragment studied in P002.
│
*)

(*              solvable_over_nat(E) ⇔ ∃ ρ : ℕ → ℕ. solves(E, ρ)              *)

Definition solvable_over_nat (eqn : h10_nd3n_equation) : Prop :=
  exists rho : valuation, solves eqn rho.

(*
│
│          A problem instance is, by definition, an equation in the
│          form fixed above. The alias is introduced so that
│          downstream files can consistently refer to `instances` at
│          the problem-theoretic layer while `equations` remains a
│          purely syntactic notion.
│
*)

Definition h10_nd3n_instance : Type := h10_nd3n_equation.

(*
│
│          Atomic yes-predicate for one low-degree equation over ℕ in
│          the current FM normal form. This remains in the premise
│          layer because local emitter files and later reductions
│          still manipulate single equations as atoms, but it is not
│          the principal semantic yes-language of P002.
│
*)

(*                h10_nd3n_yes(E) ⇔ ∃ ρ : ℕ → ℕ. solves(E, ρ)                 *)

Definition h10_nd3n_yes (eqn : h10_nd3n_instance) : Prop :=
  solvable_over_nat eqn.

(*
│
│          Neutral P002 alias for the atomic equation layer. This
│          keeps later files from having to present the local cubic
│          bound as if it were the project’s main semantic message.
│
*)

Definition p002_atomic_equation : Type := h10_nd3n_equation.
Definition p002_atomic_instance : Type := h10_nd3n_instance.
Definition p002_atomic_yes (eqn : p002_atomic_instance) : Prop :=
  h10_nd3n_yes eqn.

(*
│
│          A family instance is a finite list of atomic low-degree
│          equations, all interpreted over one common valuation. This
│          is the semantic ground truth of the current P002
│          development: the carryless Fibonacci/FM compilation layers
│          land here directly, and the later quartic route is built on
│          top of this family language rather than around it.
│
*)
(*cubic\_family\_instance ≔ [E_1,\dots,E_m],\qquad cubic\_family\_yes(\Gamma) *)
(*                    ⇔ ∃ρ.\forall E∈\Gamma,\ solves(E,ρ).                    *)

Definition cubic_family_instance : Type := list h10_nd3n_equation.

Definition cubic_family_yes (Gamma : cubic_family_instance) : Prop :=
  exists rho : valuation, Forall (fun eqn => solves eqn rho) Gamma.

(*
│
│          The principal semantic instance type of the reset P002
│          project is the family language, not the single-equation
│          language. The `p002_*` aliases below are therefore the
│          canonical project-level semantic surface; the `h10_nd3n_*`
│          names above remain available as atomic infrastructure only.
│
*)
(*        p002\_instance ≔ cubic\_family\_instance,\qquad p002\_yes ≔         *)
(*                             cubic\_family\_yes                             *)
(*  and this family layer is the base from which the quartic single-equation  *)
(*                         route is later recovered.                          *)

Definition p002_instance : Type := cubic_family_instance.
Definition p002_family_instance : Type := p002_instance.

Definition p002_yes (Gamma : p002_instance) : Prop :=
  cubic_family_yes Gamma.

Definition p002_family_yes (Gamma : p002_family_instance) : Prop :=
  p002_yes Gamma.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                       SOLVER OR METHOD DEFINITION                       ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          The classical, extensional notion of a decider: a boolean
│          function `solver` decides a yes-language `yes` when its set
│          of true-answers coincides exactly with the yes-language. No
│          computability or effectivity is asserted at this level;
│          effectivity enters only through the coded solver model
│          introduced below.
│
*)

(*                decides(yes, f) ⇔ ∀ x. f(x) = true ↔ yes(x)                 *)

Definition decides {X : Type} (yes : X -> Prop) (solver : X -> bool) : Prop :=
  forall x, solver x = true <-> yes x.

(*
│
│          Legacy specialization of the extensional decider notion to
│          the atomic single-equation language. This is not the
│          canonical project-level decider notion anymore.
│
*)

(*               decides_h10_nd3n(f) ⇔ decides(h10_nd3n_yes, f)               *)

Definition decides_h10_nd3n (solver : h10_nd3n_instance -> bool) : Prop :=
  decides h10_nd3n_yes solver.

Definition decides_cubic_family (solver : cubic_family_instance -> bool) : Prop :=
  decides cubic_family_yes solver.

Definition decides_p002 (solver : p002_instance -> bool) : Prop :=
  decides p002_yes solver.

(*
│
│          Abstract Gödel decoder: a partial function from
│          natural-number codes to semantic instances. Kept abstract
│          so that this file remains independent of any particular
│          encoding scheme. In the current FM architecture, the first
│          concrete seam where D001 enters P002 is
│          `P002_01__Architecture`, and all later compiler-correctness
│          work should route through that exported FM API rather than
│          import D001 directly.
│
*)
(*
│
│          In the intended concrete realization, the later Vector
│          Iterant layer ℑ will supply a machine-facing codec through
│          the FM machine 𝔐. The present premise file deliberately
│          does not commit to that choice: it only reserves the slot
│          in which a concrete decoder may later be proved correct.
│
*)

(*                       decode : ℕ ⇀ h10_nd3n_instance                       *)
(*   At the concrete FM seam, one later aims for a decoder of the form u ↦    *)
(*              ⌜E⌝_{ℑ,𝔐}, but P002_00 keeps this map abstract.               *)

Parameter decode_h10_nd3n_instance : nat -> option h10_nd3n_instance.

(*
│
│          The decoder is left abstract at the premise level. No
│          coverage or surjectivity property is assumed here: the
│          statement that every semantic instance is represented by
│          some code belongs to a rewrite phase or to the later
│          concrete coding realization, not to the immutable problem
│          statement.
│
*)

(*
│
│          The coded yes-language for single equations is retained as
│          legacy infrastructure around the atomic instance type. It
│          is no longer the main endpoint of P002, but it remains
│          available as part of the fixed premise vocabulary.
│
*)

(*      h10_nd3n_yes_code(u) ⇔ ∃ E. decode(u) = Some E ∧ h10_nd3n_yes(E)      *)

Definition h10_nd3n_yes_code (u : nat) : Prop :=
  exists eqn : h10_nd3n_instance,
  decode_h10_nd3n_instance u = Some eqn /\
  h10_nd3n_yes eqn.

(*
│
│          The converse transfer from the semantic yes-language to the
│          coded yes-language is intentionally absent at the premise
│          level. It requires an additional coverage hypothesis for
│          the abstract decoder, and that obligation belongs to a
│          rewrite phase or to a later concrete codec proof, not to
│          `P002_00_Premises`.
│
*)

(*
│
│          Transfer from the coded yes-language back to the semantic
│          yes-language: every yes-code exhibits a concrete
│          yes-instance together with its decoding. Note that the
│          conclusion is definitionally equal to the hypothesis —
│          `h10_nd3n_yes_code u` unfolds to exactly the existential in
│          the conclusion — so the proof closes by `exact`. The lemma
│          carries no logical content beyond its definition; it exists
│          solely to provide a stable named interface that downstream
│          files can import without depending on the raw unfolding of
│          `h10_nd3n_yes_code`.
│
*)

(*                   h10_nd3n_yes_code(u) ⇒ ∃ E. decode(u)                    *)
(*             = Some E ∧ h10_nd3n_yes(E) (definitional identity)             *)

Lemma h10_nd3n_code_yes_implies_instance_yes :
  forall u : nat,
  h10_nd3n_yes_code u ->
  exists eqn : h10_nd3n_instance,
  decode_h10_nd3n_instance u = Some eqn /\
  h10_nd3n_yes eqn.
Proof.
  intros u Hyes_code.
  exact Hyes_code.
Qed.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                           CODED SOLVER NOTION                           ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          A computational solver is modelled abstractly as a
│          natural-number code together with an evaluator `eval_code`
│          and a totality predicate `total_code`. Keeping the
│          evaluator and the totality predicate abstract, rather than
│          pinning them to a specific universal machine, ensures that
│          the results of this file apply uniformly to any reasonable
│          model of computation — Turing machines, μ-recursive
│          functions, or Rocq's own extraction target — provided it
│          exposes these two signatures.
│
*)
(*
│
│          This abstraction is exactly what allows the later FM
│          realization to plug in the execution semantics of 𝔐 without
│          changing any of the premise-layer target statements. The
│          machine model should instantiate these symbols, not rewrite
│          them.
│
*)

(*  decider_code ≔ ℕ, eval_code : ℕ → ℕ → Option Bool, total_code : ℕ → Prop  *)
(*Concrete later reading: eval_code(e,s) = Some b may be realized as “𝔐_e(s) ↓*)
(*       b”, while total_code(e) asserts that 𝔐_e halts on every input.       *)

Definition decider_code : Type := nat.
Definition eval_code_sig : Type := decider_code -> nat -> option bool.
Definition total_code_sig : Type := decider_code -> Prop.

(*
│
│          A coded decider e is correct for a yes-language P when two
│          conditions hold: (i) e is accepted by the totality
│          predicate, and (ii) its evaluator returns `Some true` on
│          exactly the yes-instances of P. The behaviour on `Some
│          false` is not postulated separately; in conjunction with
│          the totality condition below — under which every accepted
│          code terminates with some boolean answer on every input —
│          this suffices to recover an ordinary boolean decider on
│          codes, as established by
│          `correct_code_over_implies_decides`.
│
*)

(*  correct_code_over(P, eval, tot, e) ⇔ tot(e) ∧ ∀ s ∈ ℕ. eval(e, s) = Some  *)
(*                                true ↔ P(s)                                 *)

Definition correct_code_over
  (P : nat -> Prop)
  (eval_code : eval_code_sig)
  (total_code : total_code_sig)
  (e : decider_code) : Prop :=
  total_code e /\
  forall s, eval_code e s = Some true <-> P s.

(*
│
│          Totality property of the coded solver model: every code
│          accepted by the totality predicate terminates with some
│          boolean output on every input. This property is precisely
│          what distinguishes a decider code from a merely
│          semi-deciding (partial) code, and it is the crucial
│          ingredient that permits the conversion of a
│          `correct_code_over` witness into an extensional `decides`
│          witness.
│
*)

(*   coded_solver_total(eval, tot) ⇔ ∀ e, s. tot(e) ⇒ ∃ b ∈ {true, false}.    *)
(*                            eval(e, s) = Some b                             *)

Definition coded_solver_total
  (eval_code : eval_code_sig)
  (total_code : total_code_sig) : Prop :=
  forall e input,
  total_code e ->
  exists b, eval_code e input = Some b.

(*
│
│          Specialization of `correct_code_over` to the P002 coded
│          yes-language. This is the predicate whose uninhabitation is
│          established by the coded no-solver endpoint in the
│          downstream development.
│
*)

(*                 h10_nd3n_correct_code_over(eval, tot, e) ⇔                 *)
(*             correct_code_over(h10_nd3n_yes_code, eval, tot, e)             *)

Definition h10_nd3n_correct_code_over
  (eval_code : eval_code_sig)
  (total_code : total_code_sig)
  (e : decider_code) : Prop :=
  correct_code_over h10_nd3n_yes_code eval_code total_code e.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                              COMMUNICATING                              ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          Projection of a code, together with an evaluator, to an
│          ordinary boolean function ℕ → Bool. The projected function
│          returns `true` exactly when the evaluator yields `Some
│          true`, and `false` in every other case — whether `Some
│          false`, `None`, or any intermediate diverging outcome. This
│          projection constitutes the canonical bridge from the coded
│          solver model to the extensional `decides` notion.
│
*)

(*  code_to_solver(eval, e) ≔ λ s. if eval(e, s) = Some true then true else   *)
(*                                   false                                    *)

Definition code_to_solver
  (eval_code : eval_code_sig)
  (e : decider_code) : nat -> bool :=
  fun s =>
  match eval_code e s with
  | Some true => true
  | _ => false
  end.

(*
│
│          Under totality of the coded solver model, any witness of
│          `correct_code_over` for a yes-language P projects, via
│          `code_to_solver`, to a genuine extensional decider for P.
│          This lemma provides the precise sense in which the coded
│          correctness notion introduced here is conservative over the
│          classical extensional decider notion.
│
*)

(*    coded_solver_total(eval, tot) ∧ correct_code_over(P, eval, tot, e) ⇒    *)
(*                    decides(P, code_to_solver(eval, e))                     *)

Lemma correct_code_over_implies_decides :
  forall (P : nat -> Prop) eval_code total_code e,
  coded_solver_total eval_code total_code ->
  correct_code_over P eval_code total_code e ->
  decides P (code_to_solver eval_code e).
Proof.
  intros P eval_code total_code e Htot Hcorr.
  destruct Hcorr as [He_total He_corr].
  unfold decides, code_to_solver.
  intro s.
  split.
  - destruct (eval_code e s) eqn:Hev.
  + destruct b.
  * intros _.
  destruct (He_corr s) as [Hforward _].
  exact (Hforward Hev).
  * discriminate.
  + discriminate.
  - intro HP.
  destruct (Htot e s He_total) as [b Hb].
  rewrite Hb.
  destruct b.
  + reflexivity.
  + exfalso.
  destruct (He_corr s) as [_ Hbackward].
  specialize (Hbackward HP).
  rewrite Hb in Hbackward.
  discriminate.
Qed.

(*
│
│          Specialization of the preceding lemma to the P002 coded
│          yes-language. Downstream refutations show that no code can
│          satisfy the antecedent, and the present lemma is what lifts
│          those refutations from the coded model to an extensional
│          undecidability statement.
│
*)

(* coded_solver_total(eval, tot) ∧ h10_nd3n_correct_code_over(eval, tot, e) ⇒ *)
(*            decides(h10_nd3n_yes_code, code_to_solver(eval, e))             *)

Lemma h10_nd3n_correct_code_implies_decides :
  forall eval_code total_code e,
  coded_solver_total eval_code total_code ->
  h10_nd3n_correct_code_over eval_code total_code e ->
  decides h10_nd3n_yes_code (code_to_solver eval_code e).
Proof.
  intros eval_code total_code e Htot Hcorr.
  eapply correct_code_over_implies_decides.
  - exact Htot.
  - exact Hcorr.
Qed.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                            TARGET STATEMENTS                            ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          The target predicates stated below now come in two layers.
│          The atomic single-equation syntax `h10_nd3n_instance` is
│          retained because local arithmetization files speak in that
│          language. But the project-level semantic target of P002 is
│          `p002_instance`, i.e. `cubic_family_instance`,
│          satisfiability of finite families of cubic equations over
│          one shared valuation.
│
*)

Section targets.

  (*
  │
  │          Abstract instance type for unrestricted Hilbert's Tenth
  │          Problem over ℕ, together with its associated yes-predicate.
  │          Leaving these abstract allows the target statement below to
  │          be matched against any specific formalization of H10
  │          without committing to one.
  │
  *)
  
  (*          h10_n_instance : Type, h10_n_yes : h10_n_instance → Prop          *)

  Parameter h10_n_instance : Type.
  Parameter h10_n_yes : h10_n_instance -> Prop.

  (*
  │
  │          Target: unrestricted H10 over ℕ admits no extensional
  │          decider. This is the statement of the
  │          Davis–Putnam–Robinson–Matiyasevich theorem, re-expressed in
  │          the `decides` vocabulary of this file so that reductions
  │          into and out of P002 can be phrased in a uniform idiom.
  │
  *)
  
  (*  h10_n_undecidable ⇔ ∀ f : h10_n_instance → Bool. ¬ decides(h10_n_yes, f)  *)

  Definition h10_n_undecidable : Prop :=
    forall solver : h10_n_instance -> bool,
    ~ decides h10_n_yes solver.

  (*
  │
  │          Abstract instance type for the degree-two (quadratic)
  │          restriction of H10 over ℕ, together with its yes-predicate.
  │          As above, these are kept abstract so that the target
  │          statement is not tied to a specific syntax for quadratic
  │          Diophantine systems.
  │
  *)
  
  Parameter h10_quadratic_n_instance : Type.

  Parameter h10_quadratic_n_yes : h10_quadratic_n_instance -> Prop.

  (*
  │
  │          Ambient comparison target: degree-two H10 over ℕ admits an
  │          extensional decider. This abstract predicate is retained as
  │          background vocabulary only. It must not be read as
  │          asserting that the current P002 project has established a
  │          single-cubic frontier result; the live P002 certification
  │          route is family-level, and the quartic roadmap sits above
  │          it.
  │
  *)
  
  (*     h10_quadratic_n_decidable ⇔ ∃ f : h10_quadratic_n_instance → Bool.     *)
  (*                      decides(h10_quadratic_n_yes, f)                       *)

  Definition h10_quadratic_n_decidable : Prop :=
    exists solver : h10_quadratic_n_instance -> bool,
    decides h10_quadratic_n_yes solver.

End targets.

(*
│
│          Legacy single-equation endpoint retained for the atomic H10
│          fragment itself. It is not the canonical P002 endpoint and
│          must not be read as the live certification goal of the
│          current project. It remains here only because later
│          reductions still use single equations as atomic pieces
│          inside larger family- or quartic-level constructions, and
│          because the quartic route is a theorem built above the
│          family layer rather than a replacement for it at the
│          premise layer.
│
*)
(*     h10_nd3n_semantic_undecidable ⇔ ∀ f : h10_nd3n_instance → Bool. ¬      *)
(*                            decides_h10_nd3n(f)                             *)

Definition h10_nd3n_semantic_undecidable : Prop :=
  forall solver : h10_nd3n_instance -> bool,
  ~ decides_h10_nd3n solver.

(*
│
│          Principal family-level endpoint of the reset P002 project:
│          satisfiability of finite low-degree families over ℕ admits
│          no extensional decider. Later FM compilation theorems
│          should therefore land in `p002_yes`, equivalently
│          `cubic_family_yes`, not in `h10_nd3n_yes`. This is the
│          theoremically clean expression of how carryless Fibonacci
│          pairing simplifies the MRDP discipline: the hard semantic
│          work is already organized at the family level before any
│          quartic single-equation collapse is attempted.
│
*)
(*        p002\_semantic\_undecidable ⇔ ∀ f : p002\_instance → Bool. ¬        *)
(*                              decides\_p002(f)                              *)
(*cubic\_family\_semantic\_undecidable ⇔ ∀ f : cubic\_family\_instance → Bool.*)
(*                        ¬ decides\_cubic\_family(f)                         *)
(*             Later target shape: X(n) ⇔ ∃ W. Trace_{ℑ,𝔐}(n,W) ⇔             *)
(*                        p002\_yes(\Gamma_{ℑ,𝔐}(n)).                         *)

Definition p002_semantic_undecidable : Prop :=
  forall solver : p002_instance -> bool,
  ~ decides_p002 solver.

Definition p002_family_semantic_undecidable : Prop :=
  p002_semantic_undecidable.

Definition cubic_family_semantic_undecidable : Prop :=
  forall solver : cubic_family_instance -> bool,
  ~ decides_cubic_family solver.

Lemma p002_yes_iff_cubic_family_yes :
  forall Gamma,
    p002_yes Gamma <-> cubic_family_yes Gamma.
Proof.
  intro Gamma.
  unfold p002_yes.
  reflexivity.
Qed.

Lemma p002_family_yes_iff_p002_yes :
  forall Gamma,
    p002_family_yes Gamma <-> p002_yes Gamma.
Proof.
  intro Gamma.
  unfold p002_family_yes.
  reflexivity.
Qed.

Lemma decides_p002_iff_decides_cubic_family :
  forall solver,
    decides_p002 solver <-> decides_cubic_family solver.
Proof.
  intro solver.
  unfold decides_p002, decides_cubic_family, p002_yes.
  reflexivity.
Qed.

Lemma p002_semantic_undecidable_iff_cubic_family :
  p002_semantic_undecidable <-> cubic_family_semantic_undecidable.
Proof.
  unfold p002_semantic_undecidable, cubic_family_semantic_undecidable.
  unfold decides_p002, decides_cubic_family, p002_yes.
  reflexivity.
Qed.
