(*P002_03__Witness_Family_Core.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                   Proofcase / P002_03__Witness_Family_Core                   │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  This layer packages finite FM executions as single natural-number witnesses
  and fixes the core shared-valuation semantics for finite cubic families.

  The compiler-facing witness predicate is `FMValidTrace`, a raw
  natural-number predicate over encoded traces generated by `StepCode`.

  List-shaped code traces are proof helpers. The family layer below gives
  later emitters the common target relation `family_satisfiable`.

*)

From P002 Require Export P002_02__Machine_Step.
From Stdlib Require Import Bool.

(*
│
│          A code trace is a finite list of encoded machine states.
│
*)

(*                       CodeTrace ≔ List(EncodedState)                       *)

Definition CodeTrace : Type := list EncodedState.

(*
│
│          Trace encoding reuses the shared natural-list encoder.
│
*)

(*                    EncodeTrace(tr) ≔ EncodeNatList(tr)                     *)

Definition encode_code_trace : CodeTrace -> nat := encode_nat_list.

(*
│
│          The encoded-trace head projection is the shared coded-list
│          head operation.
│
*)

(*                        TraceHead(W) ≔ CodedHead(W)                         *)

Definition code_trace_head : nat -> nat := coded_list_head.

(*
│
│          The encoded-trace tail projection is the shared coded-list
│          tail operation.
│
*)

(*                        TraceTail(W) ≔ CodedTail(W)                         *)

Definition code_trace_tail : nat -> nat := coded_list_tail.

(*
│
│          The encoded-trace index projection is the shared coded-list
│          nth operation.
│
*)

(*                       TraceNth(i,W) ≔ CodedNth(i,W)                        *)

Definition code_trace_nth : nat -> nat -> nat := coded_nth.

(*
│
│          The bounded decoder unfolds at most `budget` cells and
│          stops early when the encoded witness reaches zero.
│
*)

(*                          DecodeTraceBounded(B,W)                           *)

Fixpoint decode_code_trace_bounded (budget witness : nat) : CodeTrace :=
  match budget with
  | 0 => []
  | S budget' =>
      match witness with
      | 0 => []
      | S _ =>
          code_trace_head witness ::
          decode_code_trace_bounded budget' (code_trace_tail witness)
      end
  end.

(*
│
│          The public decoder is budgeted by the witness itself, so
│          the raw number controls both payload and unfolding depth.
│
*)

(*                   DecodeTrace(W)=DecodeTraceBounded(W,W)                   *)

Definition decode_code_trace (witness : nat) : CodeTrace :=
  decode_code_trace_bounded witness witness.

(*
│
│          The start code for an input is the encoded D001 initial
│          state.
│
*)

(*                StartCode(input)=EncodeState(Initial(input))                *)

Definition start_code (input : nat) : EncodedState :=
  encode_state (initial_state input).

(*
│
│          A list trace starts from a given code when its first
│          element is that code. Empty traces do not start from
│          anything.
│
*)

(*                            StartsFrom(start,tr)                            *)

Definition CodeTraceStartsFrom (start : EncodedState) (tr : CodeTrace) : Prop :=
  match tr with
  | [] => False
  | s0 :: _ => s0 = start
  end.

(*
│
│          The executable starts-from test compares the first list
│          element with the requested start code.
│
*)

(*             StartsFromB(start,tr)=true ⇔ StartsFrom(start,tr)              *)

Definition CodeTraceStartsFrom_b (start : EncodedState) (tr : CodeTrace) : bool :=
  match tr with
  | [] => false
  | s0 :: _ => Nat.eqb s0 start
  end.

(*
│
│          A valid list trace is nonempty, follows `StepCode` on every
│          adjacent pair, and ends in a halted decoded state.
│
*)

(*       ValidTrace(prog,[s₀,…,sₙ]) ⇔ (∀ t<n. sₜ₊₁=StepCode(prog,sₜ)) ∧       *)
(*                        HaltedState(DecodeState(sₙ))                        *)

Fixpoint ValidCodeTrace (prog : MachineProgram) (tr : CodeTrace) : Prop :=
  match tr with
  | [] => False
  | s1 :: rest =>
      match rest with
      | [] => halted_state (decode_state s1)
      | s2 :: _ =>
          s2 = StepCode prog s1 /\
          ValidCodeTrace prog rest
      end
  end.

(*
│
│          The executable valid-trace checker mirrors the list
│          predicate with `step_matches_b` on adjacent pairs and
│          `halted_code_b` at the end.
│
*)

(*              ValidTraceB(prog,tr)=true ⇔ ValidTrace(prog,tr)               *)

Fixpoint ValidCodeTrace_b (prog : MachineProgram) (tr : CodeTrace) : bool :=
  match tr with
  | [] => false
  | s1 :: rest =>
      match rest with
      | [] => halted_code_b s1
      | s2 :: _ =>
          step_matches_b prog s1 s2 && ValidCodeTrace_b prog rest
      end
  end.

(*
│
│          A trace starts with an external input when it starts from
│          that input's encoded initial state.
│
*)

(*           StartsWith(input,tr) ⇔ StartsFrom(StartCode(input),tr)           *)

Definition CodeTraceStartsWith (input : nat) (tr : CodeTrace) : Prop :=
  CodeTraceStartsFrom (start_code input) tr.

(*
│
│          The executable starts-with test specializes the starts-from
│          test to the encoded initial state.
│
*)

(*           StartsWithB(input,tr)=StartsFromB(StartCode(input),tr)           *)

Definition CodeTraceStartsWith_b (input : nat) (tr : CodeTrace) : bool :=
  CodeTraceStartsFrom_b (start_code input) tr.

(*
│
│          A decoded trace witness is a list trace that starts from
│          the input, is valid, and re-encodes to the given witness
│          number.
│
*)

(*       CodeTraceWitness(prog,input,W) ⇔ ∃ tr. StartsWith(input,tr) ∧        *)
(*                  ValidTrace(prog,tr) ∧ W=EncodeTrace(tr)                   *)

Definition CodeTraceWitness
    (prog : MachineProgram) (input witness : nat) : Prop :=
  exists tr,
    CodeTraceStartsWith input tr /\
    ValidCodeTrace prog tr /\
    witness = encode_code_trace tr.

(*
│
│          The raw witness predicate starts from an explicit numeric
│          code and uses the shared bounded-run witness from D001.
│
*)

(*                        RawWitnessFrom(prog,start,W)                        *)

Definition RawCodeTraceWitnessFrom
    (prog : MachineProgram) (start witness : nat) : Prop :=
  raw_trace_witness_from
    (StepCode prog)
    (fun s => halted_state (decode_state s))
    start
    witness.

(*
│
│          The input-specialized raw witness predicate starts from
│          `StartCode input`.
│
*)

(*  RawTraceWitness(prog,input,W) ≔ RawWitnessFrom(prog,StartCode(input),W)   *)

Definition RawTraceWitness
    (prog : MachineProgram) (input witness : nat) : Prop :=
  RawCodeTraceWitnessFrom prog (start_code input) witness.

(*
│
│          The public FM trace predicate is the raw encoded-trace
│          witness notion used downstream.
│
*)

(*         FMValidTrace(prog,input,W) ≔ RawTraceWitness(prog,input,W)         *)

Definition FMValidTrace : MachineProgram -> nat -> nat -> Prop :=
  RawTraceWitness.

(*
│
│          The decoded-trace checker decodes the witness, checks the
│          start and validity conditions, and verifies that encoding
│          round-trips back to the original witness.
│
*)

(*                      CodeTraceWitnessB(prog,input,W)                       *)

Definition CodeTraceWitness_b
    (prog : MachineProgram) (input witness : nat) : bool :=
  let tr := decode_code_trace witness in
  CodeTraceStartsWith_b input tr &&
  (ValidCodeTrace_b prog tr &&
   Nat.eqb witness (encode_code_trace tr)).

(*
│
│          The executable public checker is the decoded-trace witness
│          checker.
│
*)

(*                     FMValidTraceB ≔ CodeTraceWitnessB                      *)

Definition FMValidTrace_b : MachineProgram -> nat -> nat -> bool :=
  CodeTraceWitness_b.

(*
│
│          The head projection recovers the first element of an
│          encoded nonempty trace.
│
*)

(*                     TraceHead(EncodeTrace(x :: xs))=x                      *)

Theorem encode_code_trace_cons_head :
  forall x xs,
    code_trace_head (encode_code_trace (x :: xs)) = x.
Proof.
  exact encode_nat_list_cons_head.
Qed.

(*
│
│          The tail projection recovers the encoded remainder of an
│          encoded nonempty trace.
│
*)

(*              TraceTail(EncodeTrace(x :: xs))=EncodeTrace(xs)               *)

Theorem encode_code_trace_cons_tail :
  forall x xs,
    code_trace_tail (encode_code_trace (x :: xs)) = encode_code_trace xs.
Proof.
  exact encode_nat_list_cons_tail.
Qed.

(*
│
│          Indexing into the zero code always returns the default zero
│          value.
│
*)

(*                              TraceNth(i,0)=0                               *)

Lemma code_trace_nth_zero :
  forall i,
    code_trace_nth i 0 = 0.
Proof.
  induction i as [|i IHi]; simpl.
  - reflexivity.
  - exact IHi.
Qed.

(*
│
│          Encoded trace indexing agrees with list indexing after
│          encoding.
│
*)

(*                 TraceNth(i,EncodeTrace(tr)) = nth(i,tr,0)                  *)

Theorem code_trace_nth_encode_code_trace :
  forall tr i,
    code_trace_nth i (encode_code_trace tr) = nth i tr 0.
Proof.
  intros tr i.
  revert tr.
  induction i as [|i IHi]; intros [|x xs]; simpl.
  - reflexivity.
  - apply encode_code_trace_cons_head.
  - apply code_trace_nth_zero.
  - change
      (code_trace_nth i (code_trace_tail (encode_code_trace (x :: xs))) =
       nth i xs 0).
    rewrite encode_code_trace_cons_tail.
    exact (IHi xs).
Qed.

(*
│
│          A bounded decoder with enough budget inverts trace
│          encoding.
│
*)

(*         length(tr) ≤ B ⇒ DecodeTraceBounded(B,EncodeTrace(tr))=tr          *)

Lemma decode_code_trace_bounded_encode_code_trace :
  forall tr budget,
    length tr <= budget ->
    decode_code_trace_bounded budget (encode_code_trace tr) = tr.
Proof.
  intros tr budget.
  revert tr.
  induction budget as [|budget IH]; intros [|x xs] Hlen; simpl in *.
  - reflexivity.
  - lia.
  - reflexivity.
  - change
      (code_trace_head (encode_code_trace (x :: xs)) ::
       decode_code_trace_bounded budget
         (code_trace_tail (encode_code_trace (x :: xs))) =
       x :: xs).
    rewrite encode_code_trace_cons_head.
    rewrite encode_code_trace_cons_tail.
    rewrite (IH xs) by lia.
    reflexivity.
Qed.

(*
│
│          The bounded decoder emits no more cells than its budget.
│
*)

(*                    length(DecodeTraceBounded(B,W)) ≤ B                     *)

Lemma decode_code_trace_bounded_length_le :
  forall budget witness,
    length (decode_code_trace_bounded budget witness) <= budget.
Proof.
  induction budget as [|budget IH]; intros witness; simpl.
  - lia.
  - destruct witness.
    + simpl. lia.
    + simpl.
      specialize (IH (code_trace_tail (S witness))).
      apply le_n_S.
      exact IH.
Qed.

(*
│
│          The public decoder emits no more cells than the witness
│          value used as its budget.
│
*)

(*                         length(DecodeTrace(W)) ≤ W                         *)

Lemma decode_code_trace_length_le :
  forall witness,
    length (decode_code_trace witness) <= witness.
Proof.
  intro witness.
  unfold decode_code_trace.
  apply decode_code_trace_bounded_length_le.
Qed.

(*
│
│          A nonzero witness decodes to a nonempty trace.
│
*)

(*                      W≠0 ⇒ 0 < length(DecodeTrace(W))                      *)

Lemma decode_code_trace_positive :
  forall witness,
    witness <> 0 ->
    0 < length (decode_code_trace witness).
Proof.
  intros [|witness] Hnz; [contradiction|].
  unfold decode_code_trace.
  simpl.
  lia.
Qed.

(*
│
│          Within the budget, list indexing after bounded decoding
│          agrees with numeric trace indexing.
│
*)

(*           i < B ⇒ nth(i,DecodeTraceBounded(B,W),0)=TraceNth(i,W)           *)

Lemma nth_decode_code_trace_bounded :
  forall budget witness i,
    i < budget ->
    nth i (decode_code_trace_bounded budget witness) 0 = code_trace_nth i witness.
Proof.
  induction budget as [|budget IH]; intros witness i Hi; [lia|].
  destruct witness as [|witness].
  - destruct i as [|i]; simpl.
    + reflexivity.
    + symmetry.
      apply code_trace_nth_zero.
  - destruct i as [|i]; simpl.
    + reflexivity.
    + apply IH.
      lia.
Qed.

(*
│
│          Within the decoded list length, public decoding agrees with
│          numeric trace indexing.
│
*)

(*     i < length(DecodeTrace(W)) ⇒ nth(i,DecodeTrace(W),0)=TraceNth(i,W)     *)

Lemma nth_decode_code_trace :
  forall witness i,
    i < length (decode_code_trace witness) ->
    nth i (decode_code_trace witness) 0 = code_trace_nth i witness.
Proof.
  intros witness i Hi.
  unfold decode_code_trace.
  apply nth_decode_code_trace_bounded.
  eapply Nat.lt_le_trans.
  - exact Hi.
  - apply decode_code_trace_bounded_length_le.
Qed.

(*
│
│          A singleton trace is valid exactly when its only decoded
│          state is halted.
│
*)

(*             ValidTrace(prog,[s]) ⇔ HaltedState(DecodeState(s))             *)

Lemma ValidCodeTrace_singleton :
  forall prog s,
    ValidCodeTrace prog [s] <-> halted_state (decode_state s).
Proof.
  reflexivity.
Qed.

(*
│
│          A trace with at least two states is valid exactly when the
│          first adjacent step is correct and the tail trace is valid.
│
*)

(*           ValidTrace(prog,s₁::s₂::rest) ⇔ s₂=StepCode(prog,s₁) ∧           *)
(*                         ValidTrace(prog,s₂::rest)                          *)

Lemma ValidCodeTrace_cons :
  forall prog s1 s2 rest,
    ValidCodeTrace prog (s1 :: s2 :: rest) <->
    s2 = StepCode prog s1 /\
    ValidCodeTrace prog (s2 :: rest).
Proof.
  reflexivity.
Qed.

(*
│
│          The executable valid-trace checker is logically exact.
│
*)

(*              ValidTraceB(prog,tr)=true ⇔ ValidTrace(prog,tr)               *)

Lemma ValidCodeTrace_b_correct :
  forall prog tr,
    ValidCodeTrace_b prog tr = true <->
    ValidCodeTrace prog tr.
Proof.
  intros prog tr.
  induction tr as [|s1 tr IH]; simpl.
  - split; intro H.
    + discriminate.
    + contradiction.
  - destruct tr as [|s2 rest]; simpl.
    + rewrite halted_code_b_correct.
      apply (ValidCodeTrace_singleton prog s1).
    + rewrite Bool.andb_true_iff.
      rewrite step_matches_b_correct.
      rewrite IH.
      apply (ValidCodeTrace_cons prog s1 s2 rest).
Qed.

(*
│
│          The singleton trace `[start]` starts from `start`.
│
*)

(*                         StartsFrom(start,[start])                          *)

Lemma CodeTraceStartsFrom_singleton :
  forall start,
    CodeTraceStartsFrom start [start].
Proof.
  intros start.
  reflexivity.
Qed.

(*
│
│          The executable starts-from checker is logically exact.
│
*)

(*             StartsFromB(start,tr)=true ⇔ StartsFrom(start,tr)              *)

Lemma CodeTraceStartsFrom_b_correct :
  forall start tr,
    CodeTraceStartsFrom_b start tr = true <->
    CodeTraceStartsFrom start tr.
Proof.
  intros start [|s0 rest]; simpl.
  - split; intro H.
    + discriminate.
    + contradiction.
  - rewrite Nat.eqb_eq.
    tauto.
Qed.

(*
│
│          The executable starts-with checker is logically exact.
│
*)

(*             StartsWithB(input,tr)=true ⇔ StartsWith(input,tr)              *)

Lemma CodeTraceStartsWith_b_correct :
  forall input tr,
    CodeTraceStartsWith_b input tr = true <->
    CodeTraceStartsWith input tr.
Proof.
  intros input tr.
  unfold CodeTraceStartsWith_b, CodeTraceStartsWith.
  apply CodeTraceStartsFrom_b_correct.
Qed.

(*
│
│          A concrete run trace generated from any fuel and start code
│          is nonempty.
│
*)

(*                    CodeRunTrace(next,fuel,start) ≠ nil                     *)

Lemma code_run_trace_nonempty :
  forall next fuel start,
    code_run_trace next fuel start <> [].
Proof.
  intros next fuel start.
  destruct fuel; simpl; discriminate.
Qed.

(*
│
│          The head of a concrete run trace is its start code.
│
*)

(*                 head(CodeRunTrace(next,fuel,start))=start                  *)

Lemma code_run_trace_head :
  forall next fuel start,
    hd 0 (code_run_trace next fuel start) = start.
Proof.
  intros next fuel start.
  destruct fuel; simpl; reflexivity.
Qed.

(*
│
│          The `t`-th concrete run code is the `t`-fold last-code
│          iterate, for `t` within fuel.
│
*)

(*t ≤ fuel ⇒ nth(t,CodeRunTrace(next,fuel,start),0)=CodeRunLast(next,t,start) *)

Lemma code_run_trace_nth :
  forall next fuel start t,
    t <= fuel ->
    nth t (code_run_trace next fuel start) 0 = code_run_last next t start.
Proof.
  intros next fuel.
  induction fuel as [|fuel IH]; intros start t Hle.
  - assert (t = 0) by lia.
    subst t.
    reflexivity.
  - destruct t as [|t'].
    + reflexivity.
    + simpl.
      apply IH.
      lia.
Qed.

(*
│
│          A concrete run trace generated with `fuel` has exactly
│          `fuel+1` states.
│
*)

(*                length(CodeRunTrace(next,fuel,start))=fuel+1                *)

Lemma code_run_trace_length :
  forall next fuel start,
    length (code_run_trace next fuel start) = S fuel.
Proof.
  intros next fuel.
  induction fuel as [|fuel IH]; intros start; simpl.
  - reflexivity.
  - rewrite IH.
    reflexivity.
Qed.

(*
│
│          The odd-index transform `2j−1` is at least `j` for positive
│          `j`.
│
*)

(*                              1 ≤ j ⇒ j ≤ 2j−1                              *)

Lemma two_j_minus1_ge_self :
  forall j,
    1 <= j ->
    j <= two_j_minus1 j.
Proof.
  intros j Hj.
  rewrite two_j_minus1_formula.
  lia.
Qed.

(*
│
│          Shifting a support into the odd band cannot decrease its
│          Fibonacci sum.
│
*)

(*             AllGe₂(xs) ⇒ Σfib(xs) ≤ Σfib(map(j ↦ Bx+2j−1,xs))              *)

Lemma sum_fib_odd_shift_ge :
  forall Bx xs,
    all_ge_2 xs ->
    sum_fib xs <= sum_fib (map (fun j => Bx + two_j_minus1 j) xs).
Proof.
  intros Bx xs Hge.
  induction xs as [|a xs IH]; simpl in *.
  - lia.
  - destruct Hge as [Ha Hxs].
    assert (Hidx : a <= Bx + two_j_minus1 a).
    {
      apply Nat.le_trans with (m := two_j_minus1 a).
      - apply two_j_minus1_ge_self.
        lia.
      - lia.
    }
    assert (Hfib : fib a <= fib (Bx + two_j_minus1 a)).
    {
      apply fib_le_of_le.
      exact Hidx.
    }
    specialize (IH Hxs).
    lia.
Qed.

(*
│
│          The odd-band component of an encoded pair is at least the
│          right component it represents.
│
*)

(*                          y ≤ Σfib(OddBandOf(x,y))                          *)

Lemma odd_band_of_sum_ge_right :
  forall x y,
    y <= sum_fib (odd_band_of x y).
Proof.
  intros x y.
  rewrite <- (Z0_sound y) at 1.
  unfold odd_band_of, odd_band.
  simpl.
  apply sum_fib_odd_shift_ge.
  pose proof (Z0_valid y) as [_ [_ Hge]].
  exact Hge.
Qed.

(*
│
│          Pair encoding is at least as large as its right component.
│
*)

(*                            y ≤ EncodePair(x,y)                             *)

Lemma encode_ge_right_component :
  forall x y,
    y <= encode x y.
Proof.
  intros x y.
  rewrite encode_as_sum.
  rewrite sum_fib_app.
  pose proof (odd_band_of_sum_ge_right x y) as Hodd.
  lia.
Qed.

(*
│
│          A natural-list code is at least as large as the list
│          length. This supplies enough budget for self-decoding
│          encoded traces.
│
*)

(*                       length(xs) ≤ EncodeNatList(xs)                       *)

Lemma encode_nat_list_ge_length :
  forall xs,
    length xs <= encode_nat_list xs.
Proof.
  induction xs as [|x xs IH]; simpl.
  - lia.
  - assert (Hmid : length xs <= encode x (encode_nat_list xs)).
    {
      eapply Nat.le_trans.
      - exact IH.
      - apply encode_ge_right_component.
    }
    lia.
Qed.

(*
│
│          Encoding and then decoding a code trace is the identity.
│
*)

(*                      DecodeTrace(EncodeTrace(tr))=tr                       *)

Theorem decode_code_trace_encode_code_trace :
  forall tr,
    decode_code_trace (encode_code_trace tr) = tr.
Proof.
  intros tr.
  unfold decode_code_trace.
  apply decode_code_trace_bounded_encode_code_trace.
  apply encode_nat_list_ge_length.
Qed.

(*
│
│          A concrete run whose last code is halted is a valid code
│          trace.
│
*)

(*        HaltedState(DecodeState(CodeRunLast(StepCode,fuel,start))) ⇒        *)
(*             ValidTrace(prog,CodeRunTrace(StepCode,fuel,start))             *)

Lemma code_run_trace_valid :
  forall prog fuel start,
    halted_state (decode_state (code_run_last (StepCode prog) fuel start)) ->
    ValidCodeTrace prog (code_run_trace (StepCode prog) fuel start).
Proof.
  intros prog fuel.
  induction fuel as [|fuel IH]; intros start Hhalt; simpl in *.
  - exact Hhalt.
  - destruct (code_run_trace (StepCode prog) fuel (StepCode prog start))
      as [|s2 rest] eqn:Htrace.
    + exfalso.
      apply (code_run_trace_nonempty (StepCode prog) fuel (StepCode prog start)).
      exact Htrace.
    + split.
      * pose proof (code_run_trace_head (StepCode prog) fuel (StepCode prog start))
          as Hhead.
        rewrite Htrace in Hhead.
        simpl in Hhead.
        exact Hhead.
      * rewrite <- Htrace.
        apply IH.
        exact Hhalt.
Qed.

(*
│
│          Every raw witness determines a decoded list witness.
│
*)

(*       RawTraceWitness(prog,input,W) ⇒ CodeTraceWitness(prog,input,W)       *)

Lemma RawTraceWitness_implies_CodeTraceWitness :
  forall prog input witness,
    RawTraceWitness prog input witness ->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness Hraw.
  unfold RawTraceWitness, RawCodeTraceWitnessFrom in Hraw.
  destruct Hraw as [fuel [Hwitness Hhalt]].
  exists (code_run_trace (StepCode prog) fuel (start_code input)).
  split.
  - unfold CodeTraceStartsWith.
    destruct (code_run_trace (StepCode prog) fuel (start_code input))
      as [|s0 rest] eqn:Htrace.
    + exfalso.
      apply (code_run_trace_nonempty (StepCode prog) fuel (start_code input)).
      exact Htrace.
    + pose proof (code_run_trace_head (StepCode prog) fuel (start_code input))
        as Hhead.
      rewrite Htrace in Hhead.
      simpl in Hhead.
      exact Hhead.
  - split.
    + apply code_run_trace_valid.
      exact Hhalt.
    + exact Hwitness.
Qed.

(*
│
│          A decoded list witness that starts from an explicit code
│          determines a raw bounded-run witness from that code.
│
*)

(*      StartsFrom(start,tr) ∧ ValidTrace(prog,tr) ∧ W=EncodeTrace(tr) ⇒      *)
(*                        RawWitnessFrom(prog,start,W)                        *)

Lemma CodeTraceWitness_implies_RawTraceWitnessFrom :
  forall prog start tr witness,
    CodeTraceStartsFrom start tr ->
    ValidCodeTrace prog tr ->
    witness = encode_code_trace tr ->
    RawCodeTraceWitnessFrom prog start witness.
Proof.
  intros prog start tr witness Hstart Hvalid Hwitness.
  revert start witness Hstart Hvalid Hwitness.
  induction tr as [|s1 tr IH]; intros start witness Hstart Hvalid Hwitness.
  - contradiction.
  - destruct tr as [|s2 rest].
    + simpl in Hstart, Hvalid.
      subst s1.
      unfold RawCodeTraceWitnessFrom.
      exists 0.
      simpl.
      split.
      * exact Hwitness.
      * exact Hvalid.
    + simpl in Hstart, Hvalid.
      destruct Hvalid as [Hstep Htail].
      subst s1.
      assert (Htail_start : CodeTraceStartsFrom s2 (s2 :: rest)).
      { reflexivity. }
      specialize (IH s2 _ Htail_start Htail eq_refl).
      unfold RawCodeTraceWitnessFrom in *.
      destruct IH as [fuel [Htail_witness Hhalt]].
      exists (S fuel).
      simpl.
      split.
      * rewrite Hwitness.
        simpl.
        change
          (S
             (encode start (encode_code_trace (s2 :: rest))) =
           S
             (encode start
                (encode_nat_list
                   (code_run_trace (StepCode prog) fuel (StepCode prog start))))).
        rewrite Htail_witness.
        rewrite <- Hstep.
        reflexivity.
      * rewrite <- Hstep.
        exact Hhalt.
Qed.

(*
│
│          Every decoded list witness determines the input-specialized
│          raw witness.
│
*)

(*       CodeTraceWitness(prog,input,W) ⇒ RawTraceWitness(prog,input,W)       *)

Lemma CodeTraceWitness_implies_RawTraceWitness :
  forall prog input witness,
    CodeTraceWitness prog input witness ->
    RawTraceWitness prog input witness.
Proof.
  intros prog input witness [tr [Hstart [Hvalid Hwitness]]].
  unfold RawTraceWitness.
  eapply CodeTraceWitness_implies_RawTraceWitnessFrom.
  - exact Hstart.
  - exact Hvalid.
  - exact Hwitness.
Qed.

(*
│
│          The raw encoded witness and decoded list witness predicates
│          are equivalent.
│
*)

(*       RawTraceWitness(prog,input,W) ⇔ CodeTraceWitness(prog,input,W)       *)

Theorem RawTraceWitness_iff_CodeTraceWitness :
  forall prog input witness,
    RawTraceWitness prog input witness <->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness.
  split.
  - apply RawTraceWitness_implies_CodeTraceWitness.
  - apply CodeTraceWitness_implies_RawTraceWitness.
Qed.

(*
│
│          The public FM trace predicate unfolds to the raw encoded
│          witness predicate.
│
*)

(*         FMValidTrace(prog,input,W) ⇔ RawTraceWitness(prog,input,W)         *)

Theorem FMValidTrace_unfold :
  forall prog input witness,
    FMValidTrace prog input witness <->
    RawTraceWitness prog input witness.
Proof.
  reflexivity.
Qed.

(*
│
│          The public FM trace predicate is equivalent to the decoded
│          list witness predicate.
│
*)

(*        FMValidTrace(prog,input,W) ⇔ CodeTraceWitness(prog,input,W)         *)

Theorem FMValidTrace_iff_CodeTraceWitness :
  forall prog input witness,
    FMValidTrace prog input witness <->
    CodeTraceWitness prog input witness.
Proof.
  exact RawTraceWitness_iff_CodeTraceWitness.
Qed.

(*
│
│          The decoded-trace witness checker is logically exact.
│
*)

(*   CodeTraceWitnessB(prog,input,W)=true ⇔ CodeTraceWitness(prog,input,W)    *)

Lemma CodeTraceWitness_b_correct :
  forall prog input witness,
    CodeTraceWitness_b prog input witness = true <->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness.
  unfold CodeTraceWitness_b.
  set (tr := decode_code_trace witness).
  split.
  - intro H.
    apply Bool.andb_true_iff in H.
    destruct H as [Hstart Hrest].
    apply Bool.andb_true_iff in Hrest.
    destruct Hrest as [Hvalid Heq].
    apply CodeTraceStartsWith_b_correct in Hstart.
    apply ValidCodeTrace_b_correct in Hvalid.
    apply Nat.eqb_eq in Heq.
    exists tr.
    repeat split; assumption.
  - intro H.
    destruct H as [tr' [Hstart [Hvalid Heq]]].
    subst witness.
    assert (Hdecode : decode_code_trace (encode_code_trace tr') = tr').
    {
      apply decode_code_trace_encode_code_trace.
    }
    subst tr.
    apply Bool.andb_true_iff.
    split.
    + rewrite Hdecode.
      apply CodeTraceStartsWith_b_correct.
      exact Hstart.
    + apply Bool.andb_true_iff.
      split.
      * rewrite Hdecode.
        apply ValidCodeTrace_b_correct.
        exact Hvalid.
      * apply Nat.eqb_eq.
        rewrite Hdecode.
        reflexivity.
Qed.

(*
│
│          The public FM trace checker is exact, not merely sound.
│
*)

(*       FMValidTraceB(prog,input,W)=true ⇔ FMValidTrace(prog,input,W)        *)

Theorem FMValidTrace_b_correct :
  forall prog input witness,
    FMValidTrace_b prog input witness = true <->
    FMValidTrace prog input witness.
Proof.
  intros prog input witness.
  unfold FMValidTrace_b.
  rewrite CodeTraceWitness_b_correct.
  symmetry.
  apply FMValidTrace_iff_CodeTraceWitness.
Qed.

(*
│
│          The raw explicit-start witness unfolds to a fuel, an
│          encoded concrete run, and a halted final code.
│
*)

(*                    RawWitnessFrom(prog,start,W) ⇔ ∃ T.                     *)
(*              W=EncodeTrace(CodeRunTrace(StepCode,T,start)) ∧               *)
(*          HaltedState(DecodeState(CodeRunLast(StepCode,T,start)))           *)

Lemma RawCodeTraceWitnessFrom_unfold :
  forall prog start witness,
    RawCodeTraceWitnessFrom prog start witness <->
    exists fuel,
      witness = encode_code_trace (code_run_trace (StepCode prog) fuel start) /\
      halted_state (decode_state (code_run_last (StepCode prog) fuel start)).
Proof.
  intros prog start witness.
  unfold RawCodeTraceWitnessFrom, encode_code_trace.
  reflexivity.
Qed.

(*
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║                             FAMILY SEMANTICS                            ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
*)

(*
│
│          An equation family is the premise-level cubic family
│          instance, kept under a local semantic name.
│
*)

(*                    EquationFamily ≔ CubicFamilyInstance                    *)

Definition equation_family : Type := cubic_family_instance.

(*
│
│          A family is well-formed when every equation in it is
│          well-formed.
│
*)

(*                        FamilyWF(Γ) ⇔ ∀ E ∈ Γ. WF(E)                        *)

Definition family_wf (Gamma : equation_family) : Prop :=
  Forall equation_wf Gamma.

(*
│
│          A valuation solves all equations in a family when it solves
│          each listed equation.
│
*)

(*                   SolvesAll(Γ,ρ) ⇔ ∀ E ∈ Γ. Solves(E,ρ)                    *)

Definition solves_all (Gamma : equation_family) (rho : valuation) : Prop :=
  Forall (fun eqn => solves eqn rho) Gamma.

(*
│
│          Family satisfiability is the premise-level cubic-family yes
│          predicate under the local semantic name.
│
*)

(*                      FamilySat(Γ) ≔ CubicFamilyYes(Γ)                      *)

Definition family_satisfiable (Gamma : equation_family) : Prop :=
  cubic_family_yes Gamma.

(*
│
│          The local family-satisfiable predicate is exactly
│          existential solvability by one shared valuation.
│
*)

(*                     FamilySat(Γ) ⇔ ∃ ρ. SolvesAll(Γ,ρ)                     *)

Lemma family_satisfiable_iff :
  forall Gamma,
    family_satisfiable Gamma <-> exists rho, solves_all Gamma rho.
Proof.
  intros Gamma.
  unfold family_satisfiable, cubic_family_yes, solves_all.
  reflexivity.
Qed.

(*
│
│          A monomial contributes one cubic occurrence exactly when it
│          is a cubic monomial.
│
*)

(*                         CubicMonoCount(m) ∈ {0,1}                          *)

Definition cubic_monomial_count (m : monomial) : nat :=
  match m with
  | m_cubic _ _ _ => 1
  | _ => 0
  end.

(*
│
│          A term's cubic count is the cubic count of its monomial.
│
*)

(*                 CubicTermCount(t)=CubicMonoCount(mono(t))                  *)

Definition cubic_term_count (t : term) : nat :=
  cubic_monomial_count (mono t).

(*
│
│          A polynomial's cubic count is the sum of the cubic counts
│          of its terms.
│
*)

(*                   CubicPolyCount(ts)=Σ CubicTermCount(t)                   *)

Fixpoint cubic_poly_count (ts : list term) : nat :=
  match ts with
  | [] => 0
  | t :: ts' => cubic_term_count t + cubic_poly_count ts'
  end.

(*
│
│          An equation's cubic count is the sum of its left and right
│          polynomial cubic counts.
│
*)

(*       CubicEqCount(E)=CubicPolyCount(lhs(E))+CubicPolyCount(rhs(E))        *)

Definition cubic_equation_count (eqn : h10_nd3n_equation) : nat :=
  cubic_poly_count (lhs_terms eqn) + cubic_poly_count (rhs_terms eqn).

(*
│
│          A family's cubic count is the sum of the cubic counts of
│          its equations.
│
*)

(*                   CubicFamilyCount(Γ)=Σ CubicEqCount(E)                    *)

Fixpoint cubic_family_count (Gamma : cubic_family_instance) : nat :=
  match Gamma with
  | [] => 0
  | eqn :: Gamma' => cubic_equation_count eqn + cubic_family_count Gamma'
  end.

(*
│
│          A family's variable bound is the maximum equation arity
│          appearing in the family.
│
*)

(*               FamilyVarBound(Γ)=max { varCount(E) | E ∈ Γ }                *)

Fixpoint family_var_bound (Gamma : cubic_family_instance) : nat :=
  match Gamma with
  | [] => 0
  | eqn :: Gamma' => Nat.max (var_count eqn) (family_var_bound Gamma')
  end.

(*
│
│          Cubic polynomial count distributes over list append.
│
*)

(*       CubicPolyCount(ts ++ us)=CubicPolyCount(ts)+CubicPolyCount(us)       *)

Lemma cubic_poly_count_app :
  forall ts us,
    cubic_poly_count (ts ++ us) = cubic_poly_count ts + cubic_poly_count us.
Proof.
  intros ts us.
  induction ts as [|t ts IH]; simpl.
  - reflexivity.
  - rewrite IH.
    lia.
Qed.

(*
│
│          Cubic family count distributes over family append.
│
*)

(*    CubicFamilyCount(Γ₁ ++ Γ₂)=CubicFamilyCount(Γ₁)+CubicFamilyCount(Γ₂)    *)

Lemma cubic_family_count_app :
  forall Gamma1 Gamma2,
    cubic_family_count (Gamma1 ++ Gamma2) =
    cubic_family_count Gamma1 + cubic_family_count Gamma2.
Proof.
  intros Gamma1 Gamma2.
  induction Gamma1 as [|eqn Gamma1 IH]; simpl.
  - reflexivity.
  - rewrite IH.
    lia.
Qed.

(*
│
│          The variable bound of an appended family is the maximum of
│          the two component bounds.
│
*)

(*    FamilyVarBound(Γ₁ ++ Γ₂)=max(FamilyVarBound(Γ₁),FamilyVarBound(Γ₂))     *)

Lemma family_var_bound_app :
  forall Gamma1 Gamma2,
    family_var_bound (Gamma1 ++ Gamma2) =
    Nat.max (family_var_bound Gamma1) (family_var_bound Gamma2).
Proof.
  intros Gamma1 Gamma2.
  induction Gamma1 as [|eqn Gamma1 IH]; simpl.
  - reflexivity.
  - rewrite IH.
    apply Nat.max_assoc.
Qed.

(*
│
│          Every equation arity in a family is bounded by the family
│          variable bound.
│
*)

(*                  E ∈ Γ ⇒ varCount(E) ≤ FamilyVarBound(Γ)                   *)

Lemma family_var_bound_ge_all :
  forall Gamma,
    Forall (fun eqn => var_count eqn <= family_var_bound Gamma) Gamma.
Proof.
  intro Gamma.
  induction Gamma as [|eqn Gamma IH]; simpl.
  - constructor.
  - constructor.
    + apply Nat.le_max_l.
    + apply Forall_forall.
      intros e Hin.
      rewrite Forall_forall in IH.
      pose proof (IH e Hin) as He.
      eapply Nat.le_trans.
      * exact He.
      * apply Nat.le_max_r.
Qed.

(*
│
│          The zero valuation maps every variable index to zero.
│
*)

(*                             ZeroValuation(i)=0                             *)

Definition zero_valuation : valuation := fun _ => 0.

(*
│
│          The empty family is solved by every valuation.
│
*)

(*                              SolvesAll([],ρ)                               *)

Lemma solves_all_nil :
  forall rho,
    solves_all [] rho.
Proof.
  intro rho.
  constructor.
Qed.

(*
│
│          Solving a nonempty family splits into solving its head
│          equation and its tail family.
│
*)

(*              SolvesAll(E::Γ,ρ) ⇔ Solves(E,ρ) ∧ SolvesAll(Γ,ρ)              *)

Lemma solves_all_cons :
  forall eqn Gamma rho,
    solves_all (eqn :: Gamma) rho <->
    solves eqn rho /\ solves_all Gamma rho.
Proof.
  intros eqn Gamma rho.
  split.
  - intro H.
    inversion H; subst.
    tauto.
  - intros [Heq Hrest].
    constructor; assumption.
Qed.

(*
│
│          Solving a singleton family is the same as solving its only
│          equation.
│
*)

(*                       SolvesAll([E],ρ) ⇔ Solves(E,ρ)                       *)

Lemma solves_all_singleton :
  forall eqn rho,
    solves_all [eqn] rho <->
    solves eqn rho.
Proof.
  intros eqn rho.
  rewrite solves_all_cons.
  split.
  - intros [Heq Hnil].
    exact Heq.
  - intro Heq.
    split.
    + exact Heq.
    + constructor.
Qed.

(*
│
│          Solving an appended family splits into solving both
│          component families under the same valuation.
│
*)

(*          SolvesAll(Γ₁++Γ₂,ρ) ⇔ SolvesAll(Γ₁,ρ) ∧ SolvesAll(Γ₂,ρ)           *)

Lemma solves_all_app :
  forall Gamma1 Gamma2 rho,
    solves_all (Gamma1 ++ Gamma2) rho <->
    solves_all Gamma1 rho /\ solves_all Gamma2 rho.
Proof.
  intros Gamma1 Gamma2 rho.
  induction Gamma1 as [|eqn Gamma1 IH]; simpl.
  - split.
    + intro H.
      split.
      * constructor.
      * exact H.
    + intros [_ H].
      exact H.
  - rewrite !solves_all_cons.
    rewrite IH.
    tauto.
Qed.

(*
│
│          The empty family is well-formed.
│
*)

(*                                FamilyWF([])                                *)

Lemma family_wf_nil :
  family_wf [].
Proof.
  constructor.
Qed.

(*
│
│          Well-formedness of a nonempty family splits into
│          well-formedness of its head equation and tail family.
│
*)

(*                    FamilyWF(E::Γ) ⇔ WF(E) ∧ FamilyWF(Γ)                    *)

Lemma family_wf_cons :
  forall eqn Gamma,
    family_wf (eqn :: Gamma) <->
    equation_wf eqn /\ family_wf Gamma.
Proof.
  intros eqn Gamma.
  split.
  - intro H.
    inversion H; subst.
    tauto.
  - intros [Heq Hrest].
    constructor; assumption.
Qed.

(*
│
│          Well-formedness of a singleton family is well-formedness of
│          its only equation.
│
*)

(*                           FamilyWF([E]) ⇔ WF(E)                            *)

Lemma family_wf_singleton :
  forall eqn,
    family_wf [eqn] <-> equation_wf eqn.
Proof.
  intro eqn.
  rewrite family_wf_cons.
  split.
  - intros [Heq _].
    exact Heq.
  - intro Heq.
    split.
    + exact Heq.
    + constructor.
Qed.

(*
│
│          Family well-formedness distributes over append.
│
*)

(*               FamilyWF(Γ₁++Γ₂) ⇔ FamilyWF(Γ₁) ∧ FamilyWF(Γ₂)               *)

Lemma family_wf_app :
  forall Gamma1 Gamma2,
    family_wf (Gamma1 ++ Gamma2) <->
    family_wf Gamma1 /\ family_wf Gamma2.
Proof.
  intros Gamma1 Gamma2.
  induction Gamma1 as [|eqn Gamma1 IH]; simpl.
  - split.
    + intro H.
      split.
      * constructor.
      * exact H.
    + intros [_ H].
      exact H.
  - rewrite !family_wf_cons.
    rewrite IH.
    tauto.
Qed.

(*
│
│          Any valuation that solves all equations in a family also
│          certifies that the family is well-formed, because `solves`
│          includes equation well-formedness.
│
*)

(*                        SolvesAll(Γ,ρ) ⇒ FamilyWF(Γ)                        *)

Lemma solves_all_implies_family_wf :
  forall Gamma rho,
    solves_all Gamma rho ->
    family_wf Gamma.
Proof.
  intros Gamma rho Hsolves.
  induction Hsolves as [|eqn Gamma Hsolve Hrest IH]; constructor.
  - exact (proj1 Hsolve).
  - exact IH.
Qed.

(*
│
│          The empty family is satisfiable, witnessed by the zero
│          valuation.
│
*)

(*                               FamilySat([])                                *)

Lemma family_satisfiable_nil :
  family_satisfiable [].
Proof.
  apply (proj2 (family_satisfiable_iff [])).
  exists zero_valuation.
  apply solves_all_nil.
Qed.

(*
│
│          A singleton family is satisfiable exactly when its only
│          equation is solvable over ℕ.
│
*)

(*                         FamilySat([E]) ⇔ H10Yes(E)                         *)

Lemma family_satisfiable_singleton :
  forall eqn,
    family_satisfiable [eqn] <-> h10_nd3n_yes eqn.
Proof.
  intro eqn.
  unfold h10_nd3n_yes, solvable_over_nat.
  rewrite family_satisfiable_iff.
  split.
  - intros [rho Hsingle].
    exists rho.
    apply solves_all_singleton.
    exact Hsingle.
  - intros [rho Hsolve].
    exists rho.
    apply solves_all_singleton.
    exact Hsolve.
Qed.

(*
│
│          A satisfiable nonempty family yields one shared valuation
│          solving the head equation and the tail.
│
*)

(*            FamilySat(E::Γ) ⇒ ∃ ρ. Solves(E,ρ) ∧ SolvesAll(Γ,ρ)             *)

Lemma family_satisfiable_cons :
  forall eqn Gamma,
    family_satisfiable (eqn :: Gamma) ->
    exists rho,
      solves eqn rho /\ solves_all Gamma rho.
Proof.
  intros eqn Gamma Hsat.
  apply family_satisfiable_iff in Hsat.
  destruct Hsat as [rho Hall].
  exists rho.
  now apply solves_all_cons.
Qed.

(*
│
│          Satisfiability of an appended family means one shared
│          valuation solves both component families.
│
*)

(*         FamilySat(Γ₁++Γ₂) ⇔ ∃ ρ. SolvesAll(Γ₁,ρ) ∧ SolvesAll(Γ₂,ρ)         *)

Lemma family_satisfiable_app :
  forall Gamma1 Gamma2,
    family_satisfiable (Gamma1 ++ Gamma2) <->
    exists rho, solves_all Gamma1 rho /\ solves_all Gamma2 rho.
Proof.
  intros Gamma1 Gamma2.
  rewrite family_satisfiable_iff.
  split.
  - intros [rho Hsolves].
    exists rho.
    apply solves_all_app in Hsolves.
    exact Hsolves.
  - intros [rho [Hleft Hright]].
    exists rho.
    apply solves_all_app.
    split.
    + exact Hleft.
    + exact Hright.
Qed.

(*
│
│          Every satisfiable family is well-formed.
│
*)

(*                         FamilySat(Γ) ⇒ FamilyWF(Γ)                         *)

Lemma family_satisfiable_implies_family_wf :
  forall Gamma,
    family_satisfiable Gamma ->
    family_wf Gamma.
Proof.
  intros Gamma Hsat.
  apply family_satisfiable_iff in Hsat.
  destruct Hsat as [rho Hsolves].
  now apply (solves_all_implies_family_wf Gamma rho).
Qed.
