(*@file@*)

(*@head.start@*)
(*@copyright@*)
(*@doc.proofcase@*)

(*@doc.header@[[Overview]]@*)

(*@doc.pl@[[We package finite FM executions as single natural-number witnesses in the P002 namespace.]]@*)

(*@doc.pl@[[Only one witness notion is central for the family-level compiler theorem `compile_fm_family_correct`: the numeric predicate `FMValidTrace`.]]@*)

(*@doc.pl@[[The public witness notion is the raw arithmetic witness over encoded traces generated by the fixed projected step `StepCode`. Meta-level state traces are kept only as helper interfaces, not as the compiler-facing boundary.]]@*)

(*@doc.pl@[[The asymptotic “large enough limits” semantics are intentionally deferred to the theorem-only bridge in `P002_98`. They must not enter the compiler half while equations are being constructed.]]@*)

(*@head.end@*)

From P002 Require Export P002_05__Transition_Relation.
From Stdlib Require Import Bool.

Definition StateTrace : Type := list MachineState.
Definition CodeTrace : Type := list EncodedState.

Definition encode_code_trace : CodeTrace -> nat := encode_nat_list.
Definition code_trace_head : nat -> nat := coded_list_head.
Definition code_trace_tail : nat -> nat := coded_list_tail.
Definition code_trace_nth : nat -> nat -> nat := coded_nth.

Fixpoint decode_code_trace_bounded (budget witness : nat) : CodeTrace :=
  match budget with
  | 0 => []
  | S budget' =>
      match witness with
      | 0 => []
      | S _ =>
          code_trace_head witness ::
          decode_code_trace_bounded budget' (code_trace_tail witness)
      end
  end.

Definition decode_code_trace (witness : nat) : CodeTrace :=
  decode_code_trace_bounded witness witness.

Definition trace_state_codes : StateTrace -> CodeTrace := trace_code_list.
Definition encode_state_trace : StateTrace -> nat := encode_trace.

Definition start_code (input : nat) : EncodedState :=
  encode_state (initial_state input).

Definition ValidStateTrace : MachineProgram -> StateTrace -> Prop := ValidTrace.
Definition StateTraceStartsWith (input : nat) : StateTrace -> Prop :=
  trace_starts_with input.
Definition StateTraceWitness : MachineProgram -> nat -> nat -> Prop := TraceWitness.

Definition CodeTraceStartsFrom (start : EncodedState) (tr : CodeTrace) : Prop :=
  match tr with
  | [] => False
  | s0 :: _ => s0 = start
  end.

Definition CodeTraceStartsFrom_b (start : EncodedState) (tr : CodeTrace) : bool :=
  match tr with
  | [] => false
  | s0 :: _ => Nat.eqb s0 start
  end.

Fixpoint ValidCodeTrace (prog : MachineProgram) (tr : CodeTrace) : Prop :=
  match tr with
  | [] => False
  | s1 :: rest =>
      match rest with
      | [] => halted_state (decode_state s1)
      | s2 :: _ =>
          s2 = StepCode prog s1 /\
          ValidCodeTrace prog rest
      end
  end.

Fixpoint ValidCodeTrace_b (prog : MachineProgram) (tr : CodeTrace) : bool :=
  match tr with
  | [] => false
  | s1 :: rest =>
      match rest with
      | [] => halted_code_b s1
      | s2 :: _ =>
          step_matches_b prog s1 s2 && ValidCodeTrace_b prog rest
      end
  end.

Definition CodeTraceStartsWith (input : nat) (tr : CodeTrace) : Prop :=
  CodeTraceStartsFrom (start_code input) tr.

Definition CodeTraceStartsWith_b (input : nat) (tr : CodeTrace) : bool :=
  CodeTraceStartsFrom_b (start_code input) tr.

Definition CodeTraceWitness
    (prog : MachineProgram) (input witness : nat) : Prop :=
  exists tr,
    CodeTraceStartsWith input tr /\
    ValidCodeTrace prog tr /\
    witness = encode_code_trace tr.

Definition RawCodeTraceWitnessFrom
    (prog : MachineProgram) (start witness : nat) : Prop :=
  raw_trace_witness_from
    (StepCode prog)
    (fun s => halted_state (decode_state s))
    start
    witness.

Definition RawTraceWitness
    (prog : MachineProgram) (input witness : nat) : Prop :=
  RawCodeTraceWitnessFrom prog (start_code input) witness.

Definition FMValidTrace : MachineProgram -> nat -> nat -> Prop :=
  RawTraceWitness.

Definition CodeTraceWitness_b
    (prog : MachineProgram) (input witness : nat) : bool :=
  let tr := decode_code_trace witness in
  CodeTraceStartsWith_b input tr &&
  (ValidCodeTrace_b prog tr &&
   Nat.eqb witness (encode_code_trace tr)).

Definition FMValidTrace_b : MachineProgram -> nat -> nat -> bool :=
  CodeTraceWitness_b.

(*@inline@[[`FMValidTrace_b` is the executable fixed-witness checker for the public numeric trace predicate. It matters because the family-level compiler theorem only ever quantifies over raw witness numbers, so any later attempt to replace semantic witness choice with a syntax-first search construction will have to target this checker rather than the meta-level `Prop` interface.]]@*)

Definition CanonicalTraceWitness : MachineProgram -> nat -> nat -> Prop :=
  FMValidTrace.

(*@inline@[[`FMValidTrace` is the unique public witness notion for the P002 compiler route. It is a raw natural-number predicate over encoded traces generated by repeated `StepCode`, which is exactly the shape the compiler is allowed to arithmetize. The family/limit semantics live later, outside the compiler membrane.]]@*)
(*@unicodemath@[[FMValidTrace(prog,input,W)\; \equiv\; RawTraceWitness(prog,input,W).]]@*)

Theorem encode_code_trace_cons_head :
  forall x xs,
    code_trace_head (encode_code_trace (x :: xs)) = x.
Proof.
  exact encode_nat_list_cons_head.
Qed.

Theorem encode_code_trace_cons_tail :
  forall x xs,
    code_trace_tail (encode_code_trace (x :: xs)) = encode_code_trace xs.
Proof.
  exact encode_nat_list_cons_tail.
Qed.

Lemma code_trace_nth_zero :
  forall i,
    code_trace_nth i 0 = 0.
Proof.
  induction i as [|i IHi]; simpl.
  - reflexivity.
  - exact IHi.
Qed.

Theorem code_trace_nth_encode_code_trace :
  forall tr i,
    code_trace_nth i (encode_code_trace tr) = nth i tr 0.
Proof.
  intros tr i.
  revert tr.
  induction i as [|i IHi]; intros [|x xs]; simpl.
  - reflexivity.
  - apply encode_code_trace_cons_head.
  - apply code_trace_nth_zero.
  - change
      (code_trace_nth i (code_trace_tail (encode_code_trace (x :: xs))) =
       nth i xs 0).
    rewrite encode_code_trace_cons_tail.
    exact (IHi xs).
Qed.

(*@inline@[[`code_trace_nth_encode_code_trace` turns numeric trace access back into ordinary list indexing. This is central to `compile_fm_family_correct`, because the trace-family soundness proof must recover per-time codes from the single witness number without leaving the raw numeric interface.]]@*)

Lemma decode_code_trace_bounded_encode_code_trace :
  forall tr budget,
    length tr <= budget ->
    decode_code_trace_bounded budget (encode_code_trace tr) = tr.
Proof.
  intros tr budget.
  revert tr.
  induction budget as [|budget IH]; intros [|x xs] Hlen; simpl in *.
  - reflexivity.
  - lia.
  - reflexivity.
  - change
      (code_trace_head (encode_code_trace (x :: xs)) ::
       decode_code_trace_bounded budget
         (code_trace_tail (encode_code_trace (x :: xs))) =
       x :: xs).
    rewrite encode_code_trace_cons_head.
    rewrite encode_code_trace_cons_tail.
    rewrite (IH xs) by lia.
    reflexivity.
Qed.

Lemma decode_code_trace_bounded_length_le :
  forall budget witness,
    length (decode_code_trace_bounded budget witness) <= budget.
Proof.
  induction budget as [|budget IH]; intros witness; simpl.
  - lia.
  - destruct witness.
    + simpl. lia.
    + simpl.
      specialize (IH (code_trace_tail (S witness))).
      apply le_n_S.
      exact IH.
Qed.

Lemma decode_code_trace_length_le :
  forall witness,
    length (decode_code_trace witness) <= witness.
Proof.
  intro witness.
  unfold decode_code_trace.
  apply decode_code_trace_bounded_length_le.
Qed.

Lemma decode_code_trace_positive :
  forall witness,
    witness <> 0 ->
    0 < length (decode_code_trace witness).
Proof.
  intros [|witness] Hnz; [contradiction|].
  unfold decode_code_trace.
  simpl.
  lia.
Qed.

Lemma nth_decode_code_trace_bounded :
  forall budget witness i,
    i < budget ->
    nth i (decode_code_trace_bounded budget witness) 0 = code_trace_nth i witness.
Proof.
  induction budget as [|budget IH]; intros witness i Hi; [lia|].
  destruct witness as [|witness].
  - destruct i as [|i]; simpl.
    + reflexivity.
    + symmetry.
      apply code_trace_nth_zero.
  - destruct i as [|i]; simpl.
    + reflexivity.
    + apply IH.
      lia.
Qed.

Lemma nth_decode_code_trace :
  forall witness i,
    i < length (decode_code_trace witness) ->
    nth i (decode_code_trace witness) 0 = code_trace_nth i witness.
Proof.
  intros witness i Hi.
  unfold decode_code_trace.
  apply nth_decode_code_trace_bounded.
  eapply Nat.lt_le_trans.
  - exact Hi.
  - apply decode_code_trace_bounded_length_le.
Qed.

Lemma trace_state_codes_cons :
  forall st tr,
    trace_state_codes (st :: tr) =
    encode_state st :: trace_state_codes tr.
Proof.
  reflexivity.
Qed.

Lemma encode_state_trace_cons :
  forall st tr,
    encode_state_trace (st :: tr) =
    S (encode (encode_state st) (encode_state_trace tr)).
Proof.
  exact encode_trace_cons.
Qed.

Lemma ValidStateTrace_singleton :
  forall prog st,
    ValidStateTrace prog [st] <-> halted_state st.
Proof.
  exact ValidTrace_singleton.
Qed.

Lemma ValidStateTrace_cons :
  forall prog st1 st2 rest,
    ValidStateTrace prog (st1 :: st2 :: rest) <->
    st2 = StepState prog st1 /\
    ValidStateTrace prog (st2 :: rest).
Proof.
  exact ValidTrace_cons.
Qed.

Lemma ValidCodeTrace_singleton :
  forall prog s,
    ValidCodeTrace prog [s] <-> halted_state (decode_state s).
Proof.
  reflexivity.
Qed.

Lemma ValidCodeTrace_cons :
  forall prog s1 s2 rest,
    ValidCodeTrace prog (s1 :: s2 :: rest) <->
    s2 = StepCode prog s1 /\
    ValidCodeTrace prog (s2 :: rest).
Proof.
  reflexivity.
Qed.

Lemma ValidCodeTrace_b_correct :
  forall prog tr,
    ValidCodeTrace_b prog tr = true <->
    ValidCodeTrace prog tr.
Proof.
  intros prog tr.
  induction tr as [|s1 tr IH]; simpl.
  - split; intro H.
    + discriminate.
    + contradiction.
  - destruct tr as [|s2 rest]; simpl.
    + rewrite halted_code_b_correct.
      apply (ValidCodeTrace_singleton prog s1).
    + rewrite Bool.andb_true_iff.
      rewrite step_matches_b_correct.
      rewrite IH.
      apply (ValidCodeTrace_cons prog s1 s2 rest).
Qed.

Lemma CodeTraceStartsFrom_singleton :
  forall start,
    CodeTraceStartsFrom start [start].
Proof.
  intros start.
  reflexivity.
Qed.

Lemma CodeTraceStartsFrom_b_correct :
  forall start tr,
    CodeTraceStartsFrom_b start tr = true <->
    CodeTraceStartsFrom start tr.
Proof.
  intros start [|s0 rest]; simpl.
  - split; intro H.
    + discriminate.
    + contradiction.
  - rewrite Nat.eqb_eq.
    tauto.
Qed.

Lemma CodeTraceStartsWith_b_correct :
  forall input tr,
    CodeTraceStartsWith_b input tr = true <->
    CodeTraceStartsWith input tr.
Proof.
  intros input tr.
  unfold CodeTraceStartsWith_b, CodeTraceStartsWith.
  apply CodeTraceStartsFrom_b_correct.
Qed.

Lemma code_run_trace_nonempty :
  forall next fuel start,
    code_run_trace next fuel start <> [].
Proof.
  intros next fuel start.
  destruct fuel; simpl; discriminate.
Qed.

Lemma code_run_trace_head :
  forall next fuel start,
    hd 0 (code_run_trace next fuel start) = start.
Proof.
  intros next fuel start.
  destruct fuel; simpl; reflexivity.
Qed.

Lemma code_run_trace_nth :
  forall next fuel start t,
    t <= fuel ->
    nth t (code_run_trace next fuel start) 0 = code_run_last next t start.
Proof.
  intros next fuel.
  induction fuel as [|fuel IH]; intros start t Hle.
  - assert (t = 0) by lia.
    subst t.
    reflexivity.
  - destruct t as [|t'].
    + reflexivity.
    + simpl.
      apply IH.
      lia.
Qed.

(*@inline@[[`code_run_trace_nth` identifies the `t`-th code in a concrete run trace with the `t`-step iterate returned by `code_run_last`. This is the exact bridge the compiler uses when a valuation channel is meant to name one position inside the encoded witness.]]@*)

Lemma code_run_trace_length :
  forall next fuel start,
    length (code_run_trace next fuel start) = S fuel.
Proof.
  intros next fuel.
  induction fuel as [|fuel IH]; intros start; simpl.
  - reflexivity.
  - rewrite IH.
    reflexivity.
Qed.

Lemma two_j_minus1_ge_self :
  forall j,
    1 <= j ->
    j <= two_j_minus1 j.
Proof.
  intros j Hj.
  rewrite two_j_minus1_formula.
  lia.
Qed.

Lemma sum_fib_odd_shift_ge :
  forall Bx xs,
    all_ge_2 xs ->
    sum_fib xs <= sum_fib (map (fun j => Bx + two_j_minus1 j) xs).
Proof.
  intros Bx xs Hge.
  induction xs as [|a xs IH]; simpl in *.
  - lia.
  - destruct Hge as [Ha Hxs].
    assert (Hidx : a <= Bx + two_j_minus1 a).
    {
      apply Nat.le_trans with (m := two_j_minus1 a).
      - apply two_j_minus1_ge_self.
        lia.
      - lia.
    }
    assert (Hfib : fib a <= fib (Bx + two_j_minus1 a)).
    {
      apply fib_le_of_le.
      exact Hidx.
    }
    specialize (IH Hxs).
    lia.
Qed.

Lemma odd_band_of_sum_ge_right :
  forall x y,
    y <= sum_fib (odd_band_of x y).
Proof.
  intros x y.
  rewrite <- (Z0_sound y) at 1.
  unfold odd_band_of, odd_band.
  simpl.
  apply sum_fib_odd_shift_ge.
  pose proof (Z0_valid y) as [_ [_ Hge]].
  exact Hge.
Qed.

Lemma encode_ge_right_component :
  forall x y,
    y <= encode x y.
Proof.
  intros x y.
  rewrite encode_as_sum.
  rewrite sum_fib_app.
  pose proof (odd_band_of_sum_ge_right x y) as Hodd.
  lia.
Qed.

Lemma encode_nat_list_ge_length :
  forall xs,
    length xs <= encode_nat_list xs.
Proof.
  induction xs as [|x xs IH]; simpl.
  - lia.
  - assert (Hmid : length xs <= encode x (encode_nat_list xs)).
    {
      eapply Nat.le_trans.
      - exact IH.
      - apply encode_ge_right_component.
    }
    lia.
Qed.

(*@inline@[[`encode_nat_list_ge_length` is the key numeric size bound for the fixed-witness compiler route: a coded trace is always at least as large as its list length. This is what later allows a witness-bounded primitive-recursive decoder on the raw number `W` itself.]]@*)

Theorem decode_code_trace_encode_code_trace :
  forall tr,
    decode_code_trace (encode_code_trace tr) = tr.
Proof.
  intros tr.
  unfold decode_code_trace.
  apply decode_code_trace_bounded_encode_code_trace.
  apply encode_nat_list_ge_length.
Qed.

(*@inline@[[`decode_code_trace` is the primitive-recursive fixed-witness decoder: it recovers a whole code trace from its single witness number using only a numeric budget. `decode_code_trace_encode_code_trace` is the exact adequacy theorem that later lets the compiler inspect `W` structurally without any semantic search.]]@*)

Lemma code_run_trace_valid :
  forall prog fuel start,
    halted_state (decode_state (code_run_last (StepCode prog) fuel start)) ->
    ValidCodeTrace prog (code_run_trace (StepCode prog) fuel start).
Proof.
  intros prog fuel.
  induction fuel as [|fuel IH]; intros start Hhalt; simpl in *.
  - exact Hhalt.
  - destruct (code_run_trace (StepCode prog) fuel (StepCode prog start))
      as [|s2 rest] eqn:Htrace.
    + exfalso.
      apply (code_run_trace_nonempty (StepCode prog) fuel (StepCode prog start)).
      exact Htrace.
    + split.
      * pose proof (code_run_trace_head (StepCode prog) fuel (StepCode prog start))
          as Hhead.
        rewrite Htrace in Hhead.
        simpl in Hhead.
        exact Hhead.
      * rewrite <- Htrace.
        apply IH.
        exact Hhalt.
Qed.

Lemma RawTraceWitness_implies_CodeTraceWitness :
  forall prog input witness,
    RawTraceWitness prog input witness ->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness Hraw.
  unfold RawTraceWitness, RawCodeTraceWitnessFrom in Hraw.
  destruct Hraw as [fuel [Hwitness Hhalt]].
  exists (code_run_trace (StepCode prog) fuel (start_code input)).
  split.
  - unfold CodeTraceStartsWith.
    destruct (code_run_trace (StepCode prog) fuel (start_code input))
      as [|s0 rest] eqn:Htrace.
    + exfalso.
      apply (code_run_trace_nonempty (StepCode prog) fuel (start_code input)).
      exact Htrace.
    + pose proof (code_run_trace_head (StepCode prog) fuel (start_code input))
        as Hhead.
      rewrite Htrace in Hhead.
      simpl in Hhead.
      exact Hhead.
  - split.
    + apply code_run_trace_valid.
      exact Hhalt.
    + exact Hwitness.
Qed.

Lemma CodeTraceWitness_implies_RawTraceWitnessFrom :
  forall prog start tr witness,
    CodeTraceStartsFrom start tr ->
    ValidCodeTrace prog tr ->
    witness = encode_code_trace tr ->
    RawCodeTraceWitnessFrom prog start witness.
Proof.
  intros prog start tr witness Hstart Hvalid Hwitness.
  revert start witness Hstart Hvalid Hwitness.
  induction tr as [|s1 tr IH]; intros start witness Hstart Hvalid Hwitness.
  - contradiction.
  - destruct tr as [|s2 rest].
    + simpl in Hstart, Hvalid.
      subst s1.
      unfold RawCodeTraceWitnessFrom.
      exists 0.
      simpl.
      split.
      * exact Hwitness.
      * exact Hvalid.
    + simpl in Hstart, Hvalid.
      destruct Hvalid as [Hstep Htail].
      subst s1.
      assert (Htail_start : CodeTraceStartsFrom s2 (s2 :: rest)).
      { reflexivity. }
      specialize (IH s2 _ Htail_start Htail eq_refl).
      unfold RawCodeTraceWitnessFrom in *.
      destruct IH as [fuel [Htail_witness Hhalt]].
      exists (S fuel).
      simpl.
      split.
      * rewrite Hwitness.
        simpl.
        change
          (S
             (encode start (encode_code_trace (s2 :: rest))) =
           S
             (encode start
                (encode_nat_list
                   (code_run_trace (StepCode prog) fuel (StepCode prog start))))).
        rewrite Htail_witness.
        rewrite <- Hstep.
        reflexivity.
      * rewrite <- Hstep.
        exact Hhalt.
Qed.

Lemma CodeTraceWitness_implies_RawTraceWitness :
  forall prog input witness,
    CodeTraceWitness prog input witness ->
    RawTraceWitness prog input witness.
Proof.
  intros prog input witness [tr [Hstart [Hvalid Hwitness]]].
  unfold RawTraceWitness.
  eapply CodeTraceWitness_implies_RawTraceWitnessFrom.
  - exact Hstart.
  - exact Hvalid.
  - exact Hwitness.
Qed.

Theorem RawTraceWitness_iff_CodeTraceWitness :
  forall prog input witness,
    RawTraceWitness prog input witness <->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness.
  split.
  - apply RawTraceWitness_implies_CodeTraceWitness.
  - apply CodeTraceWitness_implies_RawTraceWitness.
Qed.

Theorem FMValidTrace_unfold :
  forall prog input witness,
    FMValidTrace prog input witness <->
    RawTraceWitness prog input witness.
Proof.
  reflexivity.
Qed.

Theorem FMValidTrace_iff_CodeTraceWitness :
  forall prog input witness,
    FMValidTrace prog input witness <->
    CodeTraceWitness prog input witness.
Proof.
  exact RawTraceWitness_iff_CodeTraceWitness.
Qed.

Lemma CodeTraceWitness_b_correct :
  forall prog input witness,
    CodeTraceWitness_b prog input witness = true <->
    CodeTraceWitness prog input witness.
Proof.
  intros prog input witness.
  unfold CodeTraceWitness_b.
  set (tr := decode_code_trace witness).
  split.
  - intro H.
    apply Bool.andb_true_iff in H.
    destruct H as [Hstart Hrest].
    apply Bool.andb_true_iff in Hrest.
    destruct Hrest as [Hvalid Heq].
    apply CodeTraceStartsWith_b_correct in Hstart.
    apply ValidCodeTrace_b_correct in Hvalid.
    apply Nat.eqb_eq in Heq.
    exists tr.
    repeat split; assumption.
  - intro H.
    destruct H as [tr' [Hstart [Hvalid Heq]]].
    subst witness.
    assert (Hdecode : decode_code_trace (encode_code_trace tr') = tr').
    {
      apply decode_code_trace_encode_code_trace.
    }
    subst tr.
    apply Bool.andb_true_iff.
    split.
    + rewrite Hdecode.
      apply CodeTraceStartsWith_b_correct.
      exact Hstart.
    + apply Bool.andb_true_iff.
      split.
      * rewrite Hdecode.
        apply ValidCodeTrace_b_correct.
        exact Hvalid.
      * apply Nat.eqb_eq.
        rewrite Hdecode.
        reflexivity.
Qed.

Theorem FMValidTrace_b_correct :
  forall prog input witness,
    FMValidTrace_b prog input witness = true <->
    FMValidTrace prog input witness.
Proof.
  intros prog input witness.
  unfold FMValidTrace_b.
  rewrite CodeTraceWitness_b_correct.
  symmetry.
  apply FMValidTrace_iff_CodeTraceWitness.
Qed.

Theorem FMValidTrace_decidable :
  forall prog input witness,
    {FMValidTrace prog input witness} + {~ FMValidTrace prog input witness}.
Proof.
  intros prog input witness.
  destruct (FMValidTrace_b prog input witness) eqn:Hb.
  - left.
    apply FMValidTrace_b_correct.
    exact Hb.
  - right.
    intro Hvalid.
    apply FMValidTrace_b_correct in Hvalid.
    rewrite Hvalid in Hb.
    discriminate.
Qed.

Fixpoint search_FMValidTrace_upto
    (prog : MachineProgram) (input bound : nat) : option nat :=
  match bound with
  | 0 =>
      if FMValidTrace_b prog input 0 then Some 0 else None
  | S bound' =>
      match search_FMValidTrace_upto prog input bound' with
      | Some witness => Some witness
      | None =>
          if FMValidTrace_b prog input (S bound')
          then Some (S bound')
          else None
      end
  end.

(*@inline@[[`search_FMValidTrace_upto` is the bounded constructive search companion to `FMValidTrace_b`. It does not solve the open witness-search compiler problem by itself, but it is the exact primitive-recursive search skeleton a future syntax-first `P002_10` layer would need to mirror.]]@*)

Lemma search_FMValidTrace_upto_sound :
  forall prog input bound witness,
    search_FMValidTrace_upto prog input bound = Some witness ->
    witness <= bound /\
    FMValidTrace prog input witness.
Proof.
  intros prog input bound.
  induction bound as [|bound IH]; intros witness Hsearch; simpl in Hsearch.
  - destruct (FMValidTrace_b prog input 0) eqn:Hb.
    + assert (Hwitness : witness = 0).
      { destruct witness; simpl in Hsearch; [reflexivity|discriminate]. }
      subst witness.
      split.
      * lia.
      * apply FMValidTrace_b_correct.
        exact Hb.
    + discriminate.
  - destruct (search_FMValidTrace_upto prog input bound) as [found|] eqn:Hprev.
    + assert (Hwitness : witness = found).
      { inversion Hsearch. reflexivity. }
      subst witness.
      destruct (IH found eq_refl) as [Hle Hvalid].
      split.
      * lia.
      * exact Hvalid.
    + destruct (FMValidTrace_b prog input (S bound)) eqn:Hb.
      * assert (Hwitness : witness = S bound).
        { destruct witness; simpl in Hsearch; [discriminate|inversion Hsearch; reflexivity]. }
        subst witness.
        split.
        -- lia.
        -- apply FMValidTrace_b_correct.
           exact Hb.
      * discriminate.
Qed.

Lemma search_FMValidTrace_upto_complete :
  forall prog input bound witness,
    witness <= bound ->
    FMValidTrace prog input witness ->
    exists found,
      search_FMValidTrace_upto prog input bound = Some found /\
      FMValidTrace prog input found.
Proof.
  intros prog input bound.
  induction bound as [|bound IH]; intros witness Hle Hvalid.
  - assert (witness = 0) by lia.
    subst witness.
    exists 0.
    split.
    + assert (Hb : FMValidTrace_b prog input 0 = true).
      { apply FMValidTrace_b_correct. exact Hvalid. }
      unfold search_FMValidTrace_upto.
      rewrite Hb.
      reflexivity.
    + exact Hvalid.
  - simpl.
    destruct (Nat.eq_dec witness (S bound)) as [Heq|Hneq].
    + subst witness.
      destruct (search_FMValidTrace_upto prog input bound) as [found|] eqn:Hprev.
      * exists found.
        split.
        -- reflexivity.
        -- destruct (search_FMValidTrace_upto_sound prog input bound found Hprev)
             as [_ Hfound].
           exact Hfound.
      * rewrite (proj2 (FMValidTrace_b_correct prog input (S bound))) by exact Hvalid.
        exists (S bound).
        split.
        -- reflexivity.
        -- exact Hvalid.
    + assert (Hlt : witness <= bound) by lia.
      destruct (IH witness Hlt Hvalid) as [found [Hfound Hvalid_found]].
      rewrite Hfound.
      exists found.
      split.
      * reflexivity.
      * exact Hvalid_found.
Qed.

Theorem exists_FMValidTrace_iff_bounded_search :
  forall prog input,
    (exists witness, FMValidTrace prog input witness) <->
    (exists bound found,
        search_FMValidTrace_upto prog input bound = Some found /\
        FMValidTrace prog input found).
Proof.
  intros prog input.
  split.
  - intros [witness Hvalid].
    pose proof
      (search_FMValidTrace_upto_complete
         prog input witness witness (Nat.le_refl witness) Hvalid)
      as Hcomplete.
    destruct Hcomplete as [found [Hsearch Hfound]].
    exists witness, found.
    split.
    + exact Hsearch.
    + exact Hfound.
  - intros [bound [found [Hsearch Hvalid]]].
    exists found.
    exact Hvalid.
Qed.

Theorem CanonicalTraceWitness_unfold :
  forall prog input witness,
    CanonicalTraceWitness prog input witness <->
    FMValidTrace prog input witness.
Proof.
  reflexivity.
Qed.

(*@inline@[[`FMValidTrace_unfold` freezes the public witness boundary: later compiler theorems should target `FMValidTrace`, while state-trace and explicit code-trace lemmas remain auxiliary internal tools. This keeps the arithmetic surface numeric from the start, so the later family compiler never needs to inspect a Coq list of states.]]@*)
(*@unicodemath@[[FMValidTrace(prog,input,W)\;\Leftrightarrow\;RawTraceWitness(prog,input,W).]]@*)

Lemma RawCodeTraceWitnessFrom_unfold :
  forall prog start witness,
    RawCodeTraceWitnessFrom prog start witness <->
    exists fuel,
      witness = encode_code_trace (code_run_trace (StepCode prog) fuel start) /\
      halted_state (decode_state (code_run_last (StepCode prog) fuel start)).
Proof.
  intros prog start witness.
  unfold RawCodeTraceWitnessFrom, encode_code_trace.
  reflexivity.
Qed.

(*@inline@[[`RawCodeTraceWitnessFrom_unfold` exposes the exact arithmetic payload carried by a raw witness: a fuel bound, the encoded run generated by repeated `StepCode`, and a final halting check on the last code. This is the form the later family compiler actually consumes.]]@*)
(*@unicodemath@[[RawCodeTraceWitnessFrom(prog,start,W)\;\Leftrightarrow\;\exists T.\;W=\encode\_code\_trace(code\_run\_trace(StepCode(prog),T,start))]][[\;\wedge\;halted\_state(decode\_state(code\_run\_last(StepCode(prog),T,start))).]]@*)
