(*D001_06__Trace_Witness.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                      Proofcase / D001_06__Trace_Witness                      │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  This file packages finite execution traces as lists of encoded machine
  states.

  Its main objects are `ValidTrace`, the machine-level trace predicate on
  state lists, and the single-number witness encoding of a complete run.

*)

From D001 Require Export D001_05__Transition_Relation.

(*
│
│          `encode_nat_list` is the list-to-nat witness codec built
│          from the carryless pairing function. It is the outer shell
│          later used to store an entire execution trace as a single
│          natural number.
│
*)

Fixpoint encode_nat_list (xs : list nat) : nat :=
  match xs with
  | [] => 0
  | x :: xs' => S (encode x (encode_nat_list xs'))
  end.

Definition coded_list_head (n : nat) : nat :=
  match n with
  | 0 => 0
  | S k => fst (decode k)
  end.

Definition coded_list_tail (n : nat) : nat :=
  match n with
  | 0 => 0
  | S k => snd (decode k)
  end.

(*
│
│          `coded_nth` performs random access on the encoded-list
│          witness by iterating the extracted tail map.
│
*)

Fixpoint coded_nth (i n : nat) : nat :=
  match i with
  | 0 => coded_list_head n
  | S i' => coded_nth i' (coded_list_tail n)
  end.

(*               coded_list_head(encode_nat_list(x :: xs)) = x                *)
(*      coded_list_tail(encode_nat_list(x :: xs)) = encode_nat_list(xs).      *)

Theorem encode_nat_list_cons_head :
  forall x xs,
    coded_list_head (encode_nat_list (x :: xs)) = x.
Proof.
  intros x xs.
  change (fst (decode (encode x (encode_nat_list xs))) = x).
  rewrite decode_encode.
  reflexivity.
Qed.

Theorem encode_nat_list_cons_tail :
  forall x xs,
    coded_list_tail (encode_nat_list (x :: xs)) = encode_nat_list xs.
Proof.
  intros x xs.
  change (snd (decode (encode x (encode_nat_list xs))) = encode_nat_list xs).
  rewrite decode_encode.
  reflexivity.
Qed.

(*
│
│          `trace_code_list` projects a state trace to its
│          encoded-state sequence, and `encode_trace` then folds that
│          sequence into a single witness code.
│
*)

Definition trace_code_list (tr : list IterantState) : list nat :=
  map encode_state tr.

Definition encode_trace (tr : list IterantState) : nat :=
  encode_nat_list (trace_code_list tr).

Fixpoint code_run_last (next : nat -> nat) (fuel start : nat) : nat :=
  match fuel with
  | 0 => start
  | S fuel' => code_run_last next fuel' (next start)
  end.

Fixpoint code_run_trace (next : nat -> nat) (fuel start : nat) : list nat :=
  match fuel with
  | 0 => [start]
  | S fuel' => start :: code_run_trace next fuel' (next start)
  end.

(*
│
│          `raw_trace_witness_from` is the arithmetic-facing witness
│          predicate. It validates a raw natural-number witness by
│          requiring it to be exactly the coded trace generated by
│          iterating a numeric transition function from a start code
│          up to some halting fuel.
│
*)

(*         raw_trace_witness_from(next, halt, start, w) ⇔ ∃ fuel, w =         *)
(*            encode_nat_list(code_run_trace(next, fuel, start)) ∧            *)
(*                  halt(code_run_last(next, fuel, start)).                   *)

Definition raw_trace_witness_from
    (next : nat -> nat) (halt : nat -> Prop)
    (start witness : nat) : Prop :=
  exists fuel,
    witness = encode_nat_list (code_run_trace next fuel start) /\
    halt (code_run_last next fuel start).

(*  encode_trace(st :: tr) = 1 + encode(encode_state(st), encode_trace(tr)).  *)

Lemma encode_trace_cons :
  forall st tr,
    encode_trace (st :: tr) = S (encode (encode_state st) (encode_trace tr)).
Proof.
  reflexivity.
Qed.

Fixpoint valid_trace_states (prog : program) (tr : list IterantState) : Prop :=
  match tr with
  | [] => False
  | st1 :: rest =>
      match rest with
      | [] => halted_state st1
      | st2 :: _ =>
          st2 = step_state prog st1 /\
          valid_trace_states prog rest
      end
  end.

Definition ValidTrace : program -> list IterantState -> Prop :=
  valid_trace_states.

(*
│
│          `ValidTrace_singleton` and `ValidTrace_cons` expose the
│          trace predicate in the two operationally relevant shapes: a
│          singleton trace ends in a halted state, while a longer
│          trace advances by one valid step before recurring on the
│          tail.
│
*)

Lemma ValidTrace_singleton :
  forall prog st,
    ValidTrace prog [st] <-> halted_state st.
Proof.
  reflexivity.
Qed.

Lemma ValidTrace_cons :
  forall prog st1 st2 rest,
    ValidTrace prog (st1 :: st2 :: rest) <->
    st2 = step_state prog st1 /\
    ValidTrace prog (st2 :: rest).
Proof.
  reflexivity.
Qed.

Definition trace_starts_with (input : nat) (tr : list IterantState) : Prop :=
  match tr with
  | [] => False
  | st0 :: _ => st0 = initial_state input
  end.

(* TraceWitness(prog, input, witness) ⇔ ∃ tr, trace_starts_with(input, tr) ∧  *)
(*             ValidTrace(prog, tr) ∧ witness = encode_trace(tr).             *)

Definition TraceWitness (prog : program) (input witness : nat) : Prop :=
  exists tr,
    trace_starts_with input tr /\
    ValidTrace prog tr /\
    witness = encode_trace tr.

Definition halts_on_input (prog : program) (input : nat) : Prop :=
  exists witness, TraceWitness prog input witness.
