(* T003__QED.v *)

From Coq Require Import ZArith List.
Import ListNotations.
Open Scope Z_scope.

From T003 Require Import
  R00__VarMap
  R01__Coeff_types
  R03__Degree
  R04__Universal
  R07__Table_Inspection
  R08__Bounded_Universality.

(*************************************************************************)
(*                                                                       *)
(*    ________________________  _________________                        *)
(*    ___________________  __ \ ___  ____/__  __ \                       *)
(*    __________________  / / / __  __/  __  / / /                       *)
(*    _________________/ /_/ /___  /______  /_/ /__                      *)
(*    _________________\___\_\(_)_____/(_)_____/_(_)                     *)
(*                                                                       *)
(*    Proofcase / T003 -- QED Surface                                    *)
(*                                                                       *)
(*    This file states an exact public target, the Rocq-side criteria    *)
(*    required  by  the reductions, certifies each endpoint by direct    *)
(*    reuse, and exposes the key assumption reports.                     *)
(*                                                                       *)
(*************************************************************************)

(*************************************************************************)
(*                                                                       *)
(*                              PROPOSITIO                               *)
(*                                                                       *)
(*************************************************************************)

(*
  BOUNDED UNIVERSAL CUBIC ARTIFACT

  T003 pins one concrete cubic coefficient-table artifact generated by the
  Python constructor pipeline corresponding to the T002 compilation route.
  The pinned artifact is `U_table` over `var_count` variables with:

    - proof-length bound: `bound_n_lines = 3`
    - digit width: `bound_digit_width = 16`
    - lane width: `4` (gap-4 carryless pairing)
    - lane representation bound: `bound_max_repr_lane = 7`

  The public input code is placed at the pinned variable index `ix_u`
  (`trace_code`).

  CLAIM 1 -- DEGREE CERTIFICATION

    Every monomial in the concrete table has total degree at most `3`.
    The table is genuinely cubic: it has degree-3 monomials and maximum
    monomial degree exactly `3`.

  CLAIM 2 -- DIGEST GATE

    The representation-sensitive digest of the concrete monomial list matches
    the expected pipeline constant:
      `table_digest = table_digest_expected`.

  CLAIM 3 -- BOUNDED ENDPOINT

    For the pinned artifact and each code `t`:
      `Bounded_Thm_k t` iff there exists an admissible environment `rho` such
      that `rho` encodes `t` at the public input slot, satisfies the bounded
      representation constraints, and makes `U_table rho = 0`.

  5-step route:
    Step 1. Fix the generated table `poly` and pinned public index `ix_u`.
    Step 2. Certify the table structurally: degree bound (`R03`) and digest
            identity (`R07`).
    Step 3. Package the artifact as `UC`, exposing evaluator `U_table` and
            digest certificate.
    Step 4. Define bounded theoremhood by existence of an environment meeting
            input encoding, representation bounds, and the cubic equation.
    Step 5. Prove bounded theoremhood is exactly the solvability predicate for
            the pinned table artifact.
*)

Definition PROPOSITIO : Prop :=
  (* Claim 1: Degree certification *)
  deg_ok = true /\
  max_degree = 3%nat /\
  (max_degree <= 3)%nat /\
  (* Claim 2: Digest gate *)
  table_digest = table_digest_expected /\
  table_digest_of (uc_poly UC) = table_digest_expected /\
  (* Claim 3: Bounded endpoint *)
  (forall t,
    Bounded_Thm_k t <->
    exists rho : env,
      InputEncoding_table t rho /\
      RepresentationBound rho /\
      U_table rho = 0).

(*************************************************************************)
(*                                                                       *)
(*                                Q.E.D.                                 *)
(*                                                                       *)
(*************************************************************************)

Theorem degree_le_3_QED :
  deg_ok = true.
Proof.
  exact degree_le_3.
Qed.

Theorem max_degree_eq_3_QED :
  max_degree = 3%nat.
Proof.
  exact max_degree_eq_3.
Qed.

Theorem degree_at_most_3_QED :
  (max_degree <= 3)%nat.
Proof.
  exact degree_at_most_3.
Qed.

Theorem table_digest_ok_QED :
  table_digest = table_digest_expected.
Proof.
  exact table_digest_ok.
Qed.

Theorem bounded_endpoint_inspects_table_QED :
  table_digest_of (uc_poly UC) = table_digest_expected.
Proof.
  exact bounded_endpoint_inspects_table.
Qed.

Theorem bounded_universal_cubic_QED :
  forall t,
    Bounded_Thm_k t <->
    exists rho : env,
      InputEncoding_table t rho /\
      RepresentationBound rho /\
      U_table rho = 0.
Proof.
  exact bounded_universal_cubic.
Qed.

Theorem bounded_universal_cubic_endpoint_QED :
  forall t,
    table_digest_of (uc_poly UC) = table_digest_expected /\
    (Bounded_Thm_k t <->
      exists rho : env,
        InputEncoding_table t rho /\
        RepresentationBound rho /\
        U_table rho = 0).
Proof.
  exact bounded_universal_cubic_endpoint.
Qed.

(*************************************************************************)
(*                                                                       *)
(*                           KEY ASSUMPTION REPORT                       *)
(*                                                                       *)
(*************************************************************************)

Theorem bounded_universal_cubic_artifact_QED : PROPOSITIO.
Proof.
  refine (conj _ (conj _ (conj _ (conj _ (conj _ _))))).
  - exact degree_le_3.
  - exact max_degree_eq_3.
  - exact degree_at_most_3.
  - exact table_digest_ok.
  - exact bounded_endpoint_inspects_table.
  - exact bounded_universal_cubic.
Qed.

Print Assumptions degree_le_3_QED.
Print Assumptions table_digest_ok_QED.
Print Assumptions bounded_universal_cubic_QED.
Print Assumptions bounded_universal_cubic_endpoint_QED.
Print Assumptions bounded_universal_cubic_artifact_QED.

Redirect "theories/T003/appendix/assumptions/bounded_universal_cubic_artifact_QED"
  Print Assumptions bounded_universal_cubic_artifact_QED.
Redirect "theories/T003/appendix/assumptions/bounded_universal_cubic_endpoint_QED"
  Print Assumptions bounded_universal_cubic_endpoint_QED.
Redirect "theories/T003/appendix/assumptions/degree_le_3_QED"
  Print Assumptions degree_le_3_QED.
