(*M001_06__Syntactic_Adequacy.v*)

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      Author and Copyright remark. Author(s): │
│                ╭╮╮╮─╮                Milan Rosko  https://www.milanrosko.com │
│                ││││╭╯                Licence. This file is distributed under │
│                 ╯╯╯╰                 the Mozilla Public License Version 2.0, │
│                                      visit https://www.mozilla.org/en-US/MPL │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│                   Proofcase / M001_06__Syntactic_Adequacy                    │
└──────────────────────────────────────────────────────────────────────────────┘

  OVERVIEW

  Syntactic adequacy for checked regulator-theory derivability. The preceding
  layers define the finite proof-script checker and package successful
  scripts as `regulator_theory_checked_derivable`. This file adds the
  proof-theoretic closure relation generated by context assumptions,
  available regulator-theory axioms, and ordered modus ponens, then proves
  that the checked existential and the inductive closure are equivalent.

  The result is intentionally syntactic. It says that accepted finite proof
  scripts and the usual inductive closure present the same formulas for a
  fixed `RegulatorTheory` and context. It does not introduce semantic
  validity, model theory, modal provability, arithmetic coding, diagonal
  obstruction, or self-recognition.

*)

From M001 Require Export M001_05__Application.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                            INDUCTIVE DERIVABILITY                            │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

  `regulator_theory_inductive_derivable R Γ A` is the closure relation
  corresponding to the checker input `R; Γ`. Assumptions are read from the
  context, axiom lines are read through `available_axiom_bool R`, and MP is
  the ordinary ordered rule: from `A` and `A → B`, derive `B`. In the
  displayed judgement `⊢ᵢ`, the subscript `i` means inductive derivability
  only: it is not a semantic interpretation and not an additional
  object-language connective.

(*                             A ∈ Γ ⇒ R; Γ ⊢ᵢ A                              *)
(*                 available_axiom_bool(R,A)=true ⇒ R; Γ ⊢ᵢ A                 *)
(*                   R; Γ ⊢ᵢ A ∧ R; Γ ⊢ᵢ A → B ⇒ R; Γ ⊢ᵢ B                    *)

Inductive regulator_theory_inductive_derivable
    (R : RegulatorTheory)
    (Gamma : Context)
    : Formula -> Prop :=
| regulator_theory_inductive_assumption :
    forall A,
      In A Gamma ->
      regulator_theory_inductive_derivable R Gamma A
| regulator_theory_inductive_axiom :
    forall A,
      available_axiom_bool R A = true ->
      regulator_theory_inductive_derivable R Gamma A
| regulator_theory_inductive_mp :
    forall A B,
      regulator_theory_inductive_derivable R Gamma A ->
      regulator_theory_inductive_derivable R Gamma (Imp A B) ->
      regulator_theory_inductive_derivable R Gamma B.

(*                      R; Γ ⊬ᵢ A ≔ (R; Γ ⊢ᵢ A) → False                       *)

Definition regulator_theory_not_inductive_derivable
    (R : RegulatorTheory)
    (Gamma : Context)
    (A : Formula) : Prop :=
  regulator_theory_inductive_derivable R Gamma A -> False.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                               PREFIX SOUNDNESS                               │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

  The prefix lemmas are the bridge between indexed proof scripts and the
  inductive closure. `nth_formula` reads formulas by script index; once the
  accepted prefix is known to contain only inductively derivable lines, any
  successfully resolved index can be transported to an inductive derivation
  of the formula it names.

(*    prefix[i]=A ∧ (∀line∈prefix. R; Γ ⊢ᵢ line_formula(line)) ⇒ R; Γ ⊢ᵢ A    *)

Lemma nth_error_in_checked_prefix_lemma :
  forall (X : Type) (xs : list X) n x,
    nth_error xs n = Some x ->
    In x xs.
Proof.
  intros X xs.
  induction xs as [|head tail IH]; intros n x Hnth.
  - destruct n; discriminate Hnth.
  - destruct n as [|n'].
    + simpl in Hnth.
      inversion Hnth.
      subst.
      left.
      reflexivity.
    + simpl in Hnth.
      right.
      apply IH with (n := n').
      exact Hnth.
Qed.

Lemma nth_formula_inductive_derivable_lemma :
  forall R Gamma prefix i A,
    nth_formula prefix i = Some A ->
    (forall line,
      In line prefix ->
      regulator_theory_inductive_derivable
        R Gamma line.(line_formula)) ->
    regulator_theory_inductive_derivable R Gamma A.
Proof.
  intros R Gamma prefix i A Hnth Hprefix.
  unfold nth_formula in Hnth.
  destruct (nth_error prefix i) as [line|] eqn:Hline;
    try discriminate Hnth.
  inversion Hnth.
  subst A.
  apply Hprefix.
  apply nth_error_in_checked_prefix_lemma with (n := i).
  exact Hline.
Qed.

  A checked line is inductively sound relative to an inductively sound
  prefix. Assumption and axiom lines use the corresponding closure
  constructor directly. MP lines decode the unordered script reference
  through `mp_valid_bool_sound_unordered_lemma`, then use the ordered
  inductive MP constructor.

(*   proof_line_valid_bool(R,Γ,prefix,line)=true ∧ (∀prior∈prefix. R; Γ ⊢ᵢ    *)
(*             line_formula(prior)) ⇒ R; Γ ⊢ᵢ line_formula(line)              *)

Lemma proof_line_valid_bool_sound_inductive_lemma :
  forall R Gamma prefix line,
    proof_line_valid_bool R Gamma prefix line = true ->
    (forall prior,
      In prior prefix ->
      regulator_theory_inductive_derivable
        R Gamma prior.(line_formula)) ->
    regulator_theory_inductive_derivable
      R Gamma line.(line_formula).
Proof.
  intros R Gamma prefix line Hline Hprefix.
  destruct line as [phi just].
  destruct just as [| |i j].
  - unfold proof_line_valid_bool in Hline.
    simpl in Hline.
    apply regulator_theory_inductive_assumption.
    apply ctx_mem_bool_sound_lemma.
    exact Hline.
  - unfold proof_line_valid_bool in Hline.
    simpl in Hline.
    apply regulator_theory_inductive_axiom.
    exact Hline.
  - unfold proof_line_valid_bool in Hline.
    simpl in Hline.
    pose proof (bool_and_true_right_lemma _ _ Hline) as Hmp.
    apply mp_valid_bool_sound_unordered_lemma in Hmp.
    destruct Hmp as [A [[Hi Hj] | [Hi Hj]]].
    + apply regulator_theory_inductive_mp with (A := A).
      * apply nth_formula_inductive_derivable_lemma with
          (prefix := prefix)
          (i := i).
        -- exact Hi.
        -- exact Hprefix.
      * apply nth_formula_inductive_derivable_lemma with
          (prefix := prefix)
          (i := j).
        -- exact Hj.
        -- exact Hprefix.
    + apply regulator_theory_inductive_mp with (A := A).
      * apply nth_formula_inductive_derivable_lemma with
          (prefix := prefix)
          (i := j).
        -- exact Hj.
        -- exact Hprefix.
      * apply nth_formula_inductive_derivable_lemma with
          (prefix := prefix)
          (i := i).
        -- exact Hi.
        -- exact Hprefix.
Qed.

Lemma proof_script_check_from_bool_sound_inductive_lemma :
  forall R Gamma prefix p,
    proof_script_check_from_bool R Gamma prefix p = true ->
    (forall line,
      In line prefix ->
      regulator_theory_inductive_derivable
        R Gamma line.(line_formula)) ->
    forall line,
      In line (prefix ++ p) ->
      regulator_theory_inductive_derivable
        R Gamma line.(line_formula).
Proof.
  intros R Gamma prefix p.
  revert prefix.
  induction p as [|line rest IH]; intros prefix Hcheck Hprefix target Hin.
  - simpl in Hcheck.
    rewrite app_nil_r in Hin.
    apply Hprefix.
    exact Hin.
  - simpl in Hcheck.
    pose proof (bool_and_true_left_lemma _ _ Hcheck) as Hline.
    pose proof (bool_and_true_right_lemma _ _ Hcheck) as Hrest.
    replace (prefix ++ cons line rest)
      with ((prefix ++ cons line nil) ++ rest) in Hin.
    + apply IH with (prefix := prefix ++ cons line nil).
      * exact Hrest.
      * intros prior Hprior.
        apply in_app_or in Hprior.
        destruct Hprior as [Hprior | Hprior].
        -- apply Hprefix.
           exact Hprior.
        -- destruct Hprior as [Hhead | Hnil].
           ++ subst prior.
              apply proof_line_valid_bool_sound_inductive_lemma
                with (prefix := prefix).
              ** exact Hline.
              ** exact Hprefix.
           ++ contradiction.
      * exact Hin.
    + rewrite <- app_assoc.
      reflexivity.
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                              SYNTACTIC ADEQUACY                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

  The checked-to-inductive direction forgets the concrete script after
  extracting two facts from the Boolean checker: every line in the script
  checked successfully, and the script has a last line whose formula is the
  claimed conclusion. Prefix soundness supplies the inductive derivation of
  that last line.

(*                         R; Γ ⊢check A ⇒ R; Γ ⊢ᵢ A                          *)

Lemma regulator_theory_checked_derivable_implies_inductive_lemma :
  forall R Gamma A,
    regulator_theory_checked_derivable R Gamma A ->
    regulator_theory_inductive_derivable R Gamma A.
Proof.
  intros R Gamma A Hder.
  destruct Hder as [p Hp].
  pose proof
    (regulator_theory_check_true_lines_lemma R Gamma p A Hp)
    as Hlines.
  pose proof
    (regulator_theory_check_true_has_last_lemma R Gamma p A Hp)
    as [line [Hin Hformula]].
  pose proof
    (proof_script_check_from_bool_sound_inductive_lemma
      R Gamma nil p Hlines)
    as Hall.
  assert (Hnil :
    forall prior,
      In prior nil ->
      regulator_theory_inductive_derivable
        R Gamma prior.(line_formula)).
  {
    intros prior Hprior.
    contradiction.
  }
  specialize (Hall Hnil line).
  simpl in Hall.
  specialize (Hall Hin).
  rewrite Hformula in Hall.
  exact Hall.
Qed.

  The inductive-to-checked direction rebuilds checked witnesses constructor
  by constructor. Assumptions and available axioms use the one-line
  certificate constructors from `M001_05__Application`; MP delegates to the
  checked script-composition theorem from the same layer.

(*                         R; Γ ⊢ᵢ A ⇒ R; Γ ⊢check A                          *)

Lemma regulator_theory_inductive_derivable_implies_checked_lemma :
  forall R Gamma A,
    regulator_theory_inductive_derivable R Gamma A ->
    regulator_theory_checked_derivable R Gamma A.
Proof.
  intros R Gamma A Hder.
  induction Hder as
    [A Hin
    |A Haxiom
    |A B Harg IHarg Himp IHimp].
  - apply regulator_theory_assumption_checked_derivable_lemma.
    apply ctx_mem_bool_complete_lemma.
    exact Hin.
  - apply regulator_theory_axiom_checked_derivable_lemma.
    exact Haxiom.
  - apply regulator_theory_checked_derivable_mp_lemma with (A := A).
    + exact IHimp.
    + exact IHarg.
Qed.

Lemma regulator_theory_checked_derivable_iff_inductive_derivable_lemma :
  forall R Gamma A,
    regulator_theory_checked_derivable R Gamma A <->
    regulator_theory_inductive_derivable R Gamma A.
Proof.
  intros R Gamma A.
  split.
  - apply regulator_theory_checked_derivable_implies_inductive_lemma.
  - apply regulator_theory_inductive_derivable_implies_checked_lemma.
Qed.

(*                         R; Γ ⊢check A ⇔ R; Γ ⊢ᵢ A                          *)

Lemma regulator_theory_syntactic_adequacy_lemma :
  forall R Gamma A,
    regulator_theory_checked_derivable R Gamma A <->
    regulator_theory_inductive_derivable R Gamma A.
Proof.
  apply regulator_theory_checked_derivable_iff_inductive_derivable_lemma.
Qed.

(*                            T; Γ ⊢check_min A ⇔                             *)
(*    regulator_theory_with_axiom_set(regulator_profile_minimal,T); Γ ⊢ᵢ A    *)

Lemma regulator_theory_minimal_checked_derivable_iff_inductive_derivable_lemma :
  forall T Gamma A,
    regulator_theory_minimal_checked_derivable T Gamma A <->
    regulator_theory_inductive_derivable
      (regulator_theory_with_axiom_set regulator_profile_minimal T)
      Gamma A.
Proof.
  intros T Gamma A.
  split; intros Hder.
  - apply regulator_theory_checked_derivable_implies_inductive_lemma.
    apply regulator_theory_minimal_checked_derivable_as_theory_lemma.
    exact Hder.
  - apply regulator_theory_minimal_checked_derivable_as_theory_lemma.
    apply regulator_theory_inductive_derivable_implies_checked_lemma.
    exact Hder.
Qed.

(*profile, FT; Γ ⊢check A ⇔ finite_axiom_set_to_regulator_theory(profile,FT); *)
(*                                   Γ ⊢ᵢ A                                   *)

Lemma finite_axiom_set_checked_derivable_iff_inductive_derivable_lemma :
  forall profile T Gamma A,
    finite_axiom_set_checked_derivable profile T Gamma A <->
    regulator_theory_inductive_derivable
      (finite_axiom_set_to_regulator_theory profile T)
      Gamma A.
Proof.
  intros profile T Gamma A.
  split; intros Hder.
  - apply regulator_theory_checked_derivable_implies_inductive_lemma.
    apply finite_axiom_set_checked_derivable_as_regulator_theory_lemma.
    exact Hder.
  - apply finite_axiom_set_checked_derivable_as_regulator_theory_lemma.
    apply regulator_theory_inductive_derivable_implies_checked_lemma.
    exact Hder.
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                      CLOSURE AND FINITE-AXIOM WRAPPERS                       │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*                   R; Γ ⊢ᵢ A ∧ R; Γ ⊢ᵢ A → B ⇒ R; Γ ⊢ᵢ B                    *)

Lemma regulator_theory_inductive_derivable_mp_lemma :
  forall R Gamma A B,
    regulator_theory_inductive_derivable R Gamma A ->
    regulator_theory_inductive_derivable R Gamma (Imp A B) ->
    regulator_theory_inductive_derivable R Gamma B.
Proof.
  intros R Gamma A B Harg Himp.
  apply regulator_theory_inductive_mp with (A := A).
  - exact Harg.
  - exact Himp.
Qed.

(*        A ∈ finite_axiom_set_formulas(FT) ⇒ profile, FT; Γ ⊢check A         *)

Lemma finite_axiom_set_checked_derivable_axiom_lemma :
  forall profile T Gamma A,
    In A (finite_axiom_set_formulas T) ->
    finite_axiom_set_checked_derivable profile T Gamma A.
Proof.
  intros profile T Gamma A Hin.
  apply finite_axiom_set_checked_derivable_as_regulator_theory_lemma.
  apply regulator_theory_axiom_checked_derivable_lemma.
  unfold available_axiom_bool,
    finite_axiom_set_to_regulator_theory,
    regulator_theory_with_axiom_set,
    finite_axiom_set_to_axiom_set.
  simpl.
  pose proof
    (finite_axiom_set_contains_bool_complete_lemma T A Hin)
    as Hcontains.
  rewrite Hcontains.
  destruct (logical_axiom_bool profile A);
    reflexivity.
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                              NEGATION TRANSPORT                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

(*                         R; Γ ⊬check A ⇔ R; Γ ⊬ᵢ A                          *)

Lemma regulator_theory_not_checked_derivable_iff_not_inductive_derivable_lemma :
  forall R Gamma A,
    regulator_theory_not_checked_derivable R Gamma A <->
    regulator_theory_not_inductive_derivable R Gamma A.
Proof.
  intros R Gamma A.
  split.
  - intros Hnot HderI.
    apply Hnot.
    apply regulator_theory_inductive_derivable_implies_checked_lemma.
    exact HderI.
  - intros Hnot Hder.
    apply Hnot.
    apply regulator_theory_checked_derivable_implies_inductive_lemma.
    exact Hder.
Qed.

(*
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                             INDUCTION PRINCIPLE                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
*)

  Checked derivability inherits the induction principle of the inductive
  closure. A caller supplies handlers for assumptions, available axioms, and
  MP; the proof first transports the checked witness through syntactic
  adequacy and then performs ordinary induction on the inductive derivation.

(*  ((∀A. A∈Γ ⇒ P(A)) ∧ (∀A. available_axiom_bool(R,A)=true ⇒ P(A)) ∧ (∀A B.  *)
(*                P(A)∧P(A→B)⇒P(B))) ⇒ (R; Γ ⊢check C ⇒ P(C))                 *)

Theorem regulator_theory_checked_derivable_induction :
  forall R Gamma (P : Formula -> Prop),
    (forall A, In A Gamma -> P A) ->
    (forall A, available_axiom_bool R A = true -> P A) ->
    (forall A B, P A -> P (Imp A B) -> P B) ->
    forall C,
      regulator_theory_checked_derivable R Gamma C ->
      P C.
Proof.
  intros R Gamma P Hassumption Haxiom Hmp C Hder.
  pose proof
    (regulator_theory_checked_derivable_implies_inductive_lemma
      R Gamma C Hder) as HderI.
  clear Hder.
  induction HderI as
    [A Hin
    |A HaxiomA
    |A B Harg IHarg Himp IHimp].
  - apply Hassumption.
    exact Hin.
  - apply Haxiom.
    exact HaxiomA.
  - apply Hmp with (A := A).
    + exact IHarg.
    + exact IHimp.
Qed.
