(*@file@*)

(*@head.start@*)
(*@copyright@*)
(*@doc.proofcase@*)

(*@doc.header@[[Overview]]@*)

(*@doc.pl@[[Concrete compiled-semantics layer for L003. We partition natural-number codes into even base-machine labels and odd diagonal-product labels, define the least output relation generated by those two cases, and verify the abstract `CompilerCorrect` law for this semantics.]]@*)

(*@doc.pl@[[This is a constructive counter-machine semantics for the compiler law. The uniform compiler is the primitive-recursive map `h ↦ 2h+1`; its compiled machine runs the source evaluator on the doubled query and halts precisely on verdict `0`. A standard enumerated machine realizes the same construction by inserting `h` into this fixed program template.]]@*)

(*@head.end@*)

From L003 Require Export L003_02__Evaluator_Relative_Nonclosure.

(*@section@[[DISJOINT CODE LAYOUT]]@*)

(*@inline@[[Base-machine labels occupy the even natural numbers.]]@*)

(*@unicodemath@[[base_machine_code(n) ≔ 2n.]]@*)

Definition base_machine_code (n : nat) : Code :=
  2 * n.

(*@inline@[[A diagonal product compiled from evaluator label `h` occupies the corresponding odd code.]]@*)

(*@unicodemath@[[compiled_diagonal_code(h) ≔ 2h + 1.]]@*)

Definition compiled_diagonal_code (h : Code) : Code :=
  2 * h + 1.

(*@section@[[COMPILED OUTPUT SEMANTICS]]@*)

(*@inline@[[`CompiledOutput` is the least relation generated by two rules: a base output is transported to its even label, and an odd diagonal code emits `0` when its source evaluator emits `0` on the doubled query.]]@*)

Inductive CompiledOutput
    (base_out : OutputRelation)
    (query : QueryCoding) : OutputRelation :=
| compiled_base_output :
    forall (n : nat) (x : Input) (y : Output),
      base_out n x y ->
      CompiledOutput base_out query (base_machine_code n) x y
| compiled_diagonal_output :
    forall (h : Code) (x : Input),
      CompiledOutput base_out query h (query x x) 0 ->
      CompiledOutput base_out query (compiled_diagonal_code h) x 0.

(*@inline@[[A compiled code halts exactly when the compiled output relation has some output witness.]]@*)

Definition CompiledHalt
    (base_out : OutputRelation)
    (query : QueryCoding) : HaltingRelation :=
  fun e x => exists y : Output,
    CompiledOutput base_out query e x y.

(*@section@[[CODE SEPARATION]]@*)

(*@inline@[[Even base labels and odd diagonal-product labels are disjoint.]]@*)

Theorem base_and_diagonal_codes_disjoint :
  forall n h : nat,
    base_machine_code n <> compiled_diagonal_code h.
Proof.
  intros n h Heq.
  unfold base_machine_code, compiled_diagonal_code in Heq.
  lia.
Qed.

(*@inline@[[The odd-code embedding for diagonal products is injective.]]@*)

Theorem compiled_diagonal_code_injective :
  forall h0 h1 : Code,
    compiled_diagonal_code h0 = compiled_diagonal_code h1 ->
    h0 = h1.
Proof.
  intros h0 h1 Heq.
  unfold compiled_diagonal_code in Heq.
  lia.
Qed.

(*@section@[[COMPILER CORRECTNESS]]@*)

(*@inline@[[In the compiled semantics, the diagonal product of `h` halts on `x` exactly when `h` emits verdict `0` on the doubled query `(x,x)`.]]@*)

(*@unicodemath@[[CompiledHalt(compiled_diagonal_code(h), x)]][[⇔ CompiledOutput(h, query(x,x), 0).]]@*)

Theorem compiled_diagonal_behavior :
  forall (base_out : OutputRelation)
         (query : QueryCoding)
         (h : Code)
         (x : Input),
    CompiledHalt base_out query (compiled_diagonal_code h) x <->
    CompiledOutput base_out query h (query x x) 0.
Proof.
  intros base_out query h x.
  split.
  - intros [y Hout].
    dependent destruction Hout.
    + exfalso.
      exact (base_and_diagonal_codes_disjoint n h x).
    + apply compiled_diagonal_code_injective in x.
      subst h0.
      exact Hout.
  - intro Hzero.
    exists 0.
    apply compiled_diagonal_output.
    exact Hzero.
Qed.

(*@inline@[[The behavior theorem discharges `CompilerCorrect` uniformly for the even/odd semantics. The constructed compiler satisfies a stronger law than the abstract contract requires: its operational equivalence holds independently of the evaluator-totality premise.]]@*)

Theorem compiled_countermachine_correct :
  forall (base_out : OutputRelation)
         (query : QueryCoding),
    CompilerCorrect
      (CompiledOutput base_out query)
      (CompiledHalt base_out query)
      query
      compiled_diagonal_code.
Proof.
  intros base_out query h x Htotal.
  apply compiled_diagonal_behavior.
Qed.

(*@section@[[CONCRETE RELATIVE NONCLOSURE]]@*)

(*@inline@[[Specializing the abstract theorem to `CompiledOutput` and `CompiledHalt` establishes concrete evaluator-relative nonclosure: every evaluator satisfying `EvalC` excludes its uniformly compiled odd diagonal product from the claimed correctness domain.]]@*)

(*@unicodemath@[[EvalC(CompiledOutput, CompiledHalt, query, C, h)]][[⇒ ¬ C(compiled_diagonal_code(h)).]]@*)

Theorem concrete_evaluator_relative_nonclosure :
  forall (base_out : OutputRelation)
         (query : QueryCoding)
         (C : Code -> Prop)
         (h : Code),
    EvalC
      (CompiledOutput base_out query)
      (CompiledHalt base_out query)
      query C h ->
    ~ C (compiled_diagonal_code h).
Proof.
  intros base_out query C h Heval.
  exact
    (evaluator_relative_nonclosure
       (CompiledOutput base_out query)
       (CompiledHalt base_out query)
       query compiled_diagonal_code C h
       (compiled_countermachine_correct base_out query)
       Heval).
Qed.
