(* R07__Table_Inspection.v *)
(* Mandatory table-inspection gate for the pinned coefficient list. *)

From Coq Require Import ZArith List.
Import ListNotations.
Open Scope Z_scope.

From T003 Require Import R01__Coeff_types R02__Coefficients.

Definition digest_modulus : Z := 2305843009213693951.
Definition digest_mul_exps : Z := 65537.
Definition digest_mul_monom : Z := 2177342782468422681.
Definition digest_mul_table : Z := 1469598103934665603.

(*
  Digest is intentionally representation-sensitive over the raw `poly`
  monomial list (including monomial order and exponent-list order).
*)
Definition encode_ve (ve : nat * nat) : Z :=
  let '(v, e) := ve in
  (Z.of_nat v * 131 + Z.of_nat e + 1) mod digest_modulus.

Definition encode_exps (xs : list (nat * nat)) : Z :=
  fold_left
    (fun acc ve => (acc * digest_mul_exps + encode_ve ve) mod digest_modulus)
    xs 0.

Definition encode_monom (m : monom) : Z :=
  ((m.(coeff) mod digest_modulus) * digest_mul_monom + encode_exps m.(exps))
  mod digest_modulus.

Definition digest_step (acc : Z) (m : monom) : Z :=
  (acc * digest_mul_table + encode_monom m) mod digest_modulus.

Definition table_digest_of (p : list monom) : Z := fold_left digest_step p 0.
Definition table_digest : Z := table_digest_of poly.
(* Generated by theories/T003/python/generator/gen.py from the pinned JSON artifact. *)
Definition table_digest_expected : Z := 2026118818970225538.

Theorem table_digest_ok : table_digest = table_digest_expected.
Proof.
  vm_compute.
  reflexivity.
Qed.
